"""Portable, sequential checks of the unchanged n6 handoff; no full replay.

Usage from any directory: python /path/to/repository/n6/quick.py
Every child has a 60-second timeout. No compiler, Lean, or solver is launched.
"""
from __future__ import annotations

import hashlib
import os
from pathlib import Path, PurePosixPath
import re
import subprocess
import sys


ROOT = Path(__file__).resolve().parent
ARTIFACT = ROOT / "artifact"
MANIFEST_SHA256 = "d2fbaa2af36a8b3913a5c4c53a7592c388d3efd91ecb23a6fbc3a90b3a9f8152"
CHECKS = (
    ("verify_n6_orbits.py", "N6_CONSTRAINT_ORBITS_AND_SYMMETRIES_PASS"),
    ("n6_orbit_independent_audit.py", "N6_INDEPENDENT_ORBIT_AUDIT_PASS"),
    ("verify_n6_bilinear_rank17.py", "N6_BILINEAR_RANK17_DECOMPOSITION_PASS"),
    ("verify_n6_capacity_logs.py", "N6_EXHAUSTIVE_CAPACITY_LOGS_PASS"),
    ("audit_n6_canonicalization.py", "N6_CANONICALIZATION_CROSSCHECK_PASS"),
    ("gf2_canonical_key_property_test.py", "GF2_CANONICAL_KEY_PROPERTY_TEST_PASS"),
)


def check_hashes(root: Path = ARTIFACT) -> int:
    """Require the pinned manifest and all 50 files, including both audits.

    Hash checks authenticate this import, not the mathematical lower bound.
    """
    manifest = (root / "SHA256SUMS").read_bytes()
    if hashlib.sha256(manifest).hexdigest() != MANIFEST_SHA256:
        raise ValueError("artifact manifest differs from the supplied handoff")
    seen = set()
    for line in manifest.decode("utf-8").splitlines():
        match = re.fullmatch(r"([0-9a-f]{64})  (.+)", line)
        if match is None:
            raise ValueError("malformed checksum entry")
        expected, name = match.groups()
        relative = PurePosixPath(name)
        if relative.is_absolute() or ".." in relative.parts or "\\" in name or ":" in name:
            raise ValueError("unsafe checksum path")
        path = root.joinpath(*relative.parts).resolve()
        if not path.is_relative_to(root.resolve()) or path in seen:
            raise ValueError("escaping or duplicate checksum path")
        seen.add(path)
        if hashlib.sha256(path.read_bytes()).hexdigest() != expected:
            raise ValueError(f"checksum mismatch: {name}")
    if len(seen) != 50:
        raise ValueError("incomplete artifact manifest")
    return len(seen)


def run_check(path: Path, marker: str) -> None:
    environment = dict(os.environ, ORBIT_N="6")
    # -E ignores PYTHONOPTIMIZE/PYTHONPATH; the archived checks use assertions.
    # -B keeps the original artifact free of generated bytecode.
    result = subprocess.run(
        [sys.executable, "-E", "-B", str(path)], cwd=path.parent,
        env=environment, text=True, encoding="utf-8", errors="replace",
        capture_output=True, timeout=60, check=True,
    )
    print(result.stdout, end="", flush=True)
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr, flush=True)
    if marker not in result.stdout.splitlines():
        raise ValueError(f"missing check marker from {path.name}")


def main() -> None:
    if sys.flags.optimize:
        raise ValueError("run without -O / PYTHONOPTIMIZE; assertions must remain enabled")
    print(f"N6_ARTIFACT_SHA256_PASS files={check_hashes()}", flush=True)
    for name, marker in CHECKS:
        run_check(ARTIFACT / name, marker)
    run_check(ROOT / "verify_upper.py", "N6_SCALAR_UPPER_REPLAY_PASS")
    print("N6_QUICK_CHECKS_PASS")
    print("Lower-bound enumerations NOT replayed; no Lean or unrestricted lower bound claimed.")


if __name__ == "__main__":
    main()
