import UnrestrictedBooleanMul

/-!
# Headline theorem axiom audit

This file is compiled in CI so that the trusted assumptions of every exact
multiplicative-complexity result are printed in one stable, reviewable place.
-/

#print axioms UnrestrictedBooleanMul.mc_mul_zero
#print axioms UnrestrictedBooleanMul.mc_mul_one
#print axioms UnrestrictedBooleanMul.mc_mul_two
#print axioms UnrestrictedBooleanMul.mc_mul_three
#print axioms UnrestrictedBooleanMul.N4.no_eight_gate_circuit
#print axioms UnrestrictedBooleanMul.N4.mc_mul_four
#print axioms UnrestrictedBooleanMul.N5.mul_five_dimension_lower
#print axioms UnrestrictedBooleanMul.N5.mul_five_upper
#print axioms UnrestrictedBooleanMul.N5.zeroFiber_eq_rational
#print axioms UnrestrictedBooleanMul.N5.relationMap_finrank
#print axioms UnrestrictedBooleanMul.N5.rankTwoHankel_support
#print axioms UnrestrictedBooleanMul.N5.secant_support
#print axioms UnrestrictedBooleanMul.N5.localKlein_counts
#print axioms UnrestrictedBooleanMul.N5.effectiveFiberAtlas_card
#print axioms UnrestrictedBooleanMul.N5.target_sum_two_decomposable_rankTwo
#print axioms UnrestrictedBooleanMul.N5.effectiveFibers_eq
#print axioms UnrestrictedBooleanMul.N5.effectiveFibers_card
#print axioms UnrestrictedBooleanMul.N5.rational01_mixed_decomposableFiber_empty
#print axioms UnrestrictedBooleanMul.N5.rational02_mixed_decomposableFiber_empty
#print axioms UnrestrictedBooleanMul.N5.rational12_mixed_decomposableFiber_empty
#print axioms UnrestrictedBooleanMul.N5.rational03_mixed_decomposableFiber_empty
#print axioms UnrestrictedBooleanMul.N5.rational13_mixed_decomposableFiber_empty
#print axioms UnrestrictedBooleanMul.N5.rational23_mixed_decomposableFiber_empty
#print axioms UnrestrictedBooleanMul.N5.strongMixedPlace
#print axioms UnrestrictedBooleanMul.N5.defectCapacitySpan_eq_geometricCapacitySpan
#print axioms UnrestrictedBooleanMul.N5.targetCapacity_eq_three_add_displacement_add_gifts
#print axioms UnrestrictedBooleanMul.N5.fiberDifferenceSpace_closedPlace_le
#print axioms UnrestrictedBooleanMul.N5.rational_fiberDifference_profile
#print axioms UnrestrictedBooleanMul.N5.degreeTwo_fiberDifference_profile
#print axioms UnrestrictedBooleanMul.N5.localDisplacementSpace_eq_representedPlaceProfile
#print axioms UnrestrictedBooleanMul.N5.localDisplacementSpace_eq_activeDisplacementTwoSpace
#print axioms UnrestrictedBooleanMul.N5.displacementRank_eq_representedPlaceWeight
#print axioms UnrestrictedBooleanMul.N5.targetCapacity_eq_three_add_representedPlaceWeight_add_gifts
#print axioms UnrestrictedBooleanMul.N5.populatedRelationKernel_finrank_le_four
#print axioms UnrestrictedBooleanMul.N5.relationKernel_eq_fanoRelationSpan
#print axioms UnrestrictedBooleanMul.N5.defectRelationMap_range_eq_span_smallRelationGifts
#print axioms UnrestrictedBooleanMul.N5.fanoLine_effective_places_eq
#print axioms UnrestrictedBooleanMul.N5.fanoQuadrilateral_mixed_complement_sum_not_populated
#print axioms UnrestrictedBooleanMul.N5.relationGiftRank_eq_coefficients
#print axioms UnrestrictedBooleanMul.N5.localDisplacementCoeffSpace_finrank
#print axioms UnrestrictedBooleanMul.N5.relationGiftRank_le_six_sub_representedPlaceWeight
#print axioms UnrestrictedBooleanMul.N5.three_distinct_effective_places_linearIndependent
#print axioms UnrestrictedBooleanMul.N5.four_represented_place_points_sum_eq_zero
#print axioms UnrestrictedBooleanMul.N5.not_all_closedPlaces_represented
#print axioms UnrestrictedBooleanMul.N5.representedPlaceWeight_le_four_of_finrank_le_three
#print axioms UnrestrictedBooleanMul.N5.relationGiftCoefficientMap_eq_anchorSum
#print axioms UnrestrictedBooleanMul.N5.relationGiftRank_eq_smallAnchorGiftSpan
#print axioms UnrestrictedBooleanMul.N5.relationGiftRank_le_one_of_three_distinct_places
#print axioms UnrestrictedBooleanMul.N5.no_fanoLine_of_three_distinct_places
#print axioms UnrestrictedBooleanMul.N5.relationGiftRank_eq_zero_of_three_distinct_places_of_full_anchor_pivot
#print axioms UnrestrictedBooleanMul.N5.targetCapacity_le_seven_of_three_rational_places
#print axioms UnrestrictedBooleanMul.N5.targetCapacity_le_seven_of_no_represented_places
#print axioms UnrestrictedBooleanMul.N5.three013_S_plucker_obstruction
