name = "unrestricted_boolean_mul"
version = "0.1.0"
defaultTargets = ["UnrestrictedBooleanMul"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.32.1"

[[lean_lib]]
name = "UnrestrictedBooleanMul"
