#!/usr/bin/env python3
"""Enumerate one-constraint PGL(2,F_2) orbits for binary P_n.

The dual PGL(2,F_2) action used here is generated by coefficient reversal and
the contragredient of x -> x+1.  Set ORBIT_N in the environment to change n
from its default value six.  A nonzero n-bit mask represents a linear
constraint on the first input of binary polynomial multiplication.
"""

import os

N = int(os.environ.get("ORBIT_N", "6"))

REPRESENTATIVES = (1, 2, 4, 5, 6, 9, 10, 11, 18, 19, 27, 30, 31, 35, 39)


def translate_dual(mask: int) -> int:
    result = 0
    for i in range(N):
        # Row i has ones in positions j whose binary digits are contained in i:
        # Lucas' theorem for binomial(i,j) mod 2.
        parity = 0
        for j in range(i + 1):
            if (i & j) == j:
                parity ^= (mask >> j) & 1
        result |= parity << i
    return result


def reverse(mask: int) -> int:
    return sum(((mask >> i) & 1) << (N - 1 - i) for i in range(N))


def orbit(seed: int) -> frozenset[int]:
    result = {seed}
    pending = [seed]
    while pending:
        mask = pending.pop()
        for image in (translate_dual(mask), reverse(mask)):
            if image not in result:
                result.add(image)
                pending.append(image)
    return frozenset(result)


def main() -> None:
    orbits: list[frozenset[int]] = []
    covered: set[int] = set()
    for mask in range(1, 1 << N):
        if mask not in covered:
            current = orbit(mask)
            orbits.append(current)
            covered.update(current)

    minima = tuple(min(current) for current in orbits)
    if N == 6:
        assert len(orbits) == 15
        assert minima == REPRESENTATIVES
    assert covered == set(range(1, 1 << N))
    assert sum(map(len, orbits)) == (1 << N) - 1

    print(f"n={N} orbits={len(orbits)} covered={(1 << N) - 1} representatives="
          + ",".join(map(str, minima)))
    print("sizes=" + ",".join(str(len(current)) for current in orbits))


if __name__ == "__main__":
    main()
