import UnrestrictedBooleanMul.N5.CircuitSuffix
import UnrestrictedBooleanMul.N5.CostedReplay
import UnrestrictedBooleanMul.N5.QuadraticPrefixExact

/-!
# Replay from an intrinsic quadratic capacity state

An all-quadratic prefix is contained in the intrinsic capacity span of the
quotient defect generated by its flattened decomposable presentation.  This
module proves that the larger state has exactly the same quotient defect and
therefore supports the existing equal-defect suffix simulation.

This is the structural core of capacity replay.  It uses submodule images and
rank-nullity only; no circuit or truth-table enumeration is involved.
-/

namespace UnrestrictedBooleanMul
namespace N5

noncomputable section

/-- Quotient projection restricted to the intrinsic capacity span of a
decomposable presentation. -/
def intrinsicCapacityProjection {j : Nat} (p : Fin j → TwoForm) :
    defectCapacitySpan (presentationDefect p) →ₗ[F₂] QuadraticQuotient :=
  quadraticQuotientProjection.domRestrict
    (defectCapacitySpan (presentationDefect p))

private theorem defectCapacitySpan_projection_le
    (Q : Submodule F₂ QuadraticQuotient) :
    defectCapacitySpan Q ≤ Q.comap quadraticQuotientProjection := by
  apply sup_le
  · intro d hd
    change quadraticQuotientProjection d ∈ Q
    have hdTarget := localDisplacementSpace_le_targetTwoSpace Q hd
    rw [(quadraticQuotientProjection_eq_zero_iff d).2 hdTarget]
    exact Submodule.zero_mem Q
  · rw [Submodule.span_le]
    rintro d ⟨q, rfl⟩
    change quadraticQuotientProjection (populatedLift q) ∈ Q
    rw [populatedLift_projection]
    exact q.1.2

/-- The intrinsic capacity span of a decomposable presentation has quotient
image exactly the presentation defect. -/
theorem intrinsicCapacityProjection_range {j : Nat}
    (p : Fin j → TwoForm) (hdec : ∀ i, IsDecomposableTwo (p i)) :
    LinearMap.range (intrinsicCapacityProjection p) = presentationDefect p := by
  apply le_antisymm
  · rintro y ⟨x, rfl⟩
    exact defectCapacitySpan_projection_le (presentationDefect p) x.2
  · apply Submodule.span_le.mpr
    rintro q ⟨i, rfl⟩
    by_cases hzero : quadraticQuotientProjection (p i) = 0
    · change quadraticQuotientProjection (p i) ∈
        LinearMap.range (intrinsicCapacityProjection p)
      rw [hzero]
      exact Submodule.zero_mem _
    · let x : PopulatedPoint (presentationDefect p) :=
        ⟨⟨quadraticQuotientProjection (p i),
            Submodule.subset_span ⟨i, rfl⟩⟩,
          hzero, ⟨p i, hdec i, rfl⟩⟩
      refine ⟨⟨populatedLift x, ?_⟩, ?_⟩
      · exact Submodule.mem_sup_right
          (Submodule.subset_span ⟨x, rfl⟩)
      · change quadraticQuotientProjection (populatedLift x) =
          quadraticQuotientProjection (p i)
        rw [populatedLift_projection]
        rfl

theorem intrinsicCapacityProjection_ker {j : Nat} (p : Fin j → TwoForm) :
    LinearMap.ker (intrinsicCapacityProjection p) =
      targetTwoSpace.comap (defectCapacitySpan (presentationDefect p)).subtype := by
  ext x
  simp [intrinsicCapacityProjection, quadraticQuotientProjection_eq_zero_iff]

/-- The Boolean lift of the intrinsic quadratic capacity span. -/
def intrinsicCapacityState {j : Nat} (p : Fin j → TwoForm) :
    Submodule F₂ (ANF 10) :=
  E2.quadraticEnvelopeState (defectCapacitySpan (presentationDefect p))

/-- There are no populated nonzero points in the zero defect space. -/
theorem isEmpty_populatedPoint_bot :
    IsEmpty (PopulatedPoint (⊥ : Submodule F₂ QuadraticQuotient)) := by
  constructor
  intro q
  have hq : q.1.1 = 0 := by simpa using q.1.2
  exact q.2.1 hq

/-- At quadratic defect zero the intrinsic capacity is exactly the three
rational target directions.  This is an equality of spaces, not merely the
dimension-three capacity bound. -/
theorem defectCapacitySpan_bot :
    defectCapacitySpan (⊥ : Submodule F₂ QuadraticQuotient) =
      rationalTwoSpace := by
  rw [defectCapacitySpan_eq_geometricCapacitySpan]
  apply le_antisymm
  · rw [geometricCapacitySpan]
    apply sup_le le_rfl
    rw [Submodule.span_le]
    intro p hp
    rcases hp with ⟨q, _hq⟩
    exact False.elim (isEmpty_populatedPoint_bot.false q)
  · exact le_sup_left

/-- A presentation with zero quotient defect therefore has the canonical
anchor-free intrinsic state `Aff + R`. -/
theorem intrinsicCapacityState_eq_rational_of_defectRank_zero
    {j : Nat} (p : Fin j → TwoForm)
    (hzero : Module.finrank F₂ (presentationDefect p) = 0) :
    intrinsicCapacityState p =
      E2.quadraticEnvelopeState rationalTwoSpace := by
  have hbot : presentationDefect p = ⊥ :=
    Submodule.finrank_eq_zero.mp hzero
  rw [intrinsicCapacityState, hbot, defectCapacitySpan_bot]

theorem targetCapacity_eq_three_of_finrank_eq_zero
    (Q : Submodule F₂ QuadraticQuotient)
    (hzero : Module.finrank F₂ Q = 0) :
    targetCapacity Q = 3 := by
  have hbot : Q = ⊥ := Submodule.finrank_eq_zero.mp hzero
  rw [targetCapacity, hbot, defectCapacitySpan_bot,
    inf_eq_right.mpr rationalTwoSpace_le_targetTwoSpace,
    rationalTwoSpace_finrank]

theorem affine_le_intrinsicCapacityState {j : Nat} (p : Fin j → TwoForm) :
    affine 10 ≤ intrinsicCapacityState p :=
  E2.affine_le_quadraticEnvelopeState _

/-- The target rank of the lifted state is the intrinsic target capacity. -/
theorem intrinsicCapacityState_targetRank {j : Nat} (p : Fin j → TwoForm) :
    stateTargetRank (intrinsicCapacityState p) =
      targetCapacity (presentationDefect p) := by
  rw [stateTargetRank, intrinsicCapacityState,
    E2.quadraticEnvelopeState_targetRank, targetCapacity, inf_comm]

theorem intrinsicCapacityState_targetRank_eq_three_of_defectRank_zero
    {j : Nat} (p : Fin j → TwoForm)
    (hzero : Module.finrank F₂ (presentationDefect p) = 0) :
    stateTargetRank (intrinsicCapacityState p) = 3 := by
  rw [intrinsicCapacityState_targetRank,
    targetCapacity_eq_three_of_finrank_eq_zero _ hzero]

/-- Rank-nullity identifies the quotient defect of the capacity state with
the dimension of the presentation defect. -/
theorem intrinsicCapacityState_defectRank {j : Nat}
    (p : Fin j → TwoForm) (hdec : ∀ i, IsDecomposableTwo (p i)) :
    N4.flagDefectRank (intrinsicCapacityState p) (mulTarget 5) =
      Module.finrank F₂ (presentationDefect p) := by
  let W := defectCapacitySpan (presentationDefect p)
  let f := intrinsicCapacityProjection p
  have hrange : LinearMap.range f = presentationDefect p :=
    intrinsicCapacityProjection_range p hdec
  have hker : LinearMap.ker f = targetTwoSpace.comap W.subtype := by
    exact intrinsicCapacityProjection_ker p
  let e : ↥(targetTwoSpace.comap W.subtype) ≃ₗ[F₂]
      ↥(W ⊓ targetTwoSpace) := {
    toFun x := ⟨x.1.1, x.1.2, x.2⟩
    invFun x := ⟨⟨x.1, x.2.1⟩, x.2.2⟩
    left_inv _ := rfl
    right_inv _ := rfl
    map_add' _ _ := rfl
    map_smul' _ _ := rfl
  }
  have hkerRank : Module.finrank F₂ (LinearMap.ker f) =
      Module.finrank F₂ ↥(W ⊓ targetTwoSpace) := by
    rw [hker]
    exact e.finrank_eq
  have hrank := f.finrank_range_add_finrank_ker
  rw [hrange, hkerRank] at hrank
  change Module.finrank F₂ (presentationDefect p) +
      Module.finrank F₂ ↥(W ⊓ targetTwoSpace) =
        Module.finrank F₂ W at hrank
  change N4.flagDefectRank (E2.quadraticEnvelopeState W) (mulTarget 5) = _
  rw [E2.quadraticEnvelopeState_defectRank]
  omega

/-- An all-quadratic prefix is contained in the capacity state of its exact
flattened presentation. -/
theorem circuitFlag_le_intrinsicCapacityState_of_allQuadratic
    {r j : Nat} (C : Circuit 10 r)
    (hflat : QuadraticPrefixFlattening C j)
    (hall : ∀ i : Fin r, i.val < j →
      C.gate i ∈ N4.quadraticANFSpace 10) :
    N4.circuitFlag C j ≤ intrinsicCapacityState hflat.generator := by
  apply circuitFlag_le_quadraticEnvelopeState_of_allQuadratic C hall
  rw [← hflat.span_eq, defectCapacitySpan_eq_geometricCapacitySpan]
  exact decomposablePresentationSpan_le_geometricCapacitySpan
    hflat.generator hflat.decomposable

/-- The prefix and its intrinsic capacity enlargement have equal quotient
defect. -/
theorem circuitFlag_intrinsicCapacityState_equal_defect
    {r j : Nat} (C : Circuit 10 r)
    (hflat : QuadraticPrefixFlattening C j)
    (hall : ∀ i : Fin r, i.val < j →
      C.gate i ∈ N4.quadraticANFSpace 10) :
    N4.flagDefectRank (N4.circuitFlag C j) (mulTarget 5) =
      N4.flagDefectRank (intrinsicCapacityState hflat.generator)
        (mulTarget 5) := by
  rw [intrinsicCapacityState_defectRank hflat.generator hflat.decomposable,
    quadraticPrefixFlattening_defect_eq_flagDefect C hflat hall]

/-- Replay any defect-legal suffix from the larger intrinsic capacity state.
The endpoint is the sum of the capacity state and the original endpoint, so
it contains every target obtained by the original suffix. -/
theorem DefectLegalSuffix.replay_from_intrinsicCapacityState
    {r j : Nat} (C : Circuit 10 r)
    (hflat : QuadraticPrefixFlattening C j)
    (hall : ∀ i : Fin r, i.val < j →
      C.gate i ∈ N4.quadraticANFSpace 10)
    {V : Submodule F₂ (ANF 10)}
    (hreach : DefectLegalSuffix (N4.circuitFlag C j) V) :
    DefectLegalSuffix (intrinsicCapacityState hflat.generator)
      (intrinsicCapacityState hflat.generator ⊔ V) := by
  apply hreach.simulate_from_equal_defect
    (circuitFlag_le_intrinsicCapacityState_of_allQuadratic C hflat hall)
    (circuitFlag_intrinsicCapacityState_equal_defect C hflat hall)
  rw [← circuitFlag_intrinsicCapacityState_equal_defect C hflat hall]
  exact (flagDefectRank_mono hreach.start_le).trans
    hreach.final_defect_le_three

/-- Cost-preserving form of intrinsic-capacity replay.  Gates made redundant
by the capacity enlargement are deleted, and the retained gate count is
certified by exact dimension growth. -/
theorem CostedDefectLegalSuffix.prune_replay_from_intrinsicCapacityState
    {r j k : Nat} (C : Circuit 10 r)
    (hflat : QuadraticPrefixFlattening C j)
    (hall : ∀ i : Fin r, i.val < j →
      C.gate i ∈ N4.quadraticANFSpace 10)
    {V : Submodule F₂ (ANF 10)}
    (hreach : CostedDefectLegalSuffix (N4.circuitFlag C j) k V)
    (hbaseDef : N4.flagDefectRank (N4.circuitFlag C j)
      (mulTarget 5) ≤ 3) :
    ∃ k' ≤ k,
      CostedDefectLegalSuffix (intrinsicCapacityState hflat.generator) k'
        (intrinsicCapacityState hflat.generator ⊔ V) ∧
      Module.finrank F₂ (intrinsicCapacityState hflat.generator ⊔ V) =
        Module.finrank F₂ (intrinsicCapacityState hflat.generator) + k' := by
  apply hreach.prune_simulate_from_equal_defect
    (circuitFlag_le_intrinsicCapacityState_of_allQuadratic C hflat hall)
    (circuitFlag_intrinsicCapacityState_equal_defect C hflat hall)
  rw [← circuitFlag_intrinsicCapacityState_equal_defect C hflat hall]
  exact hbaseDef

end
end N5
end UnrestrictedBooleanMul
