import UnrestrictedBooleanMul.N5.DefectThreeWitness

/-!
# The capacity obstruction

This module connects a finite decomposable quadratic presentation to the
closed-place capacity developed in the preceding files.  The argument is
pure linear algebra: project the presentation span to the quadratic quotient,
identify the kernel with the nine-dimensional Hankel target, and observe that
every decomposable generator belongs to the geometric capacity span of the
resulting defect subspace.
-/

namespace UnrestrictedBooleanMul
namespace N5

noncomputable section

/-- The span of a finite family of quadratic products. -/
def decomposablePresentationSpan {j : Nat} (p : Fin j → TwoForm) :
    Submodule F₂ TwoForm :=
  Submodule.span F₂ (Set.range p)

/-- The quotient defect generated by a finite quadratic presentation. -/
def presentationDefect {j : Nat} (p : Fin j → TwoForm) :
    Submodule F₂ QuadraticQuotient :=
  Submodule.span F₂
    (Set.range fun i => quadraticQuotientProjection (p i))

theorem rational_targetTwo_mem (c : TargetCoeff)
    (hc : c ∈ rationalCoeffSpace) :
    targetTwo c ∈ rationalTwoSpace := by
  exact ⟨c, hc, rfl⟩

/-- Every decomposable point in the zero quotient fiber is already in the
three-dimensional rational target space. -/
theorem zeroFiber_le_rationalTwoSpace {p : TwoForm}
    (hdec : IsDecomposableTwo p)
    (hp : quadraticQuotientProjection p = 0) :
    p ∈ rationalTwoSpace := by
  have hfiber : p ∈ decomposableFiber 0 := ⟨hdec, hp⟩
  rw [zeroFiber_eq_rational] at hfiber
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hfiber
  rcases hfiber with rfl | rfl | rfl | rfl
  · exact Submodule.zero_mem _
  · apply rational_targetTwo_mem
    exact Submodule.subset_span (by simp)
  · apply rational_targetTwo_mem
    exact Submodule.subset_span (by simp)
  · apply rational_targetTwo_mem
    exact Submodule.subset_span (by simp)

/-- A decomposable generator belongs to the geometric capacity span of the
defect subspace generated by the whole presentation. -/
theorem decomposable_mem_geometricCapacitySpan {j : Nat}
    (p : Fin j → TwoForm) (hdec : ∀ i, IsDecomposableTwo (p i)) (i : Fin j) :
    p i ∈ geometricCapacitySpan (presentationDefect p) := by
  let q := quadraticQuotientProjection (p i)
  have hqQ : q ∈ presentationDefect p := by
    apply Submodule.subset_span
    exact ⟨i, rfl⟩
  by_cases hq0 : q = 0
  · apply (le_sup_left : rationalTwoSpace ≤
      geometricCapacitySpan (presentationDefect p))
    exact zeroFiber_le_rationalTwoSpace (hdec i) hq0
  · apply (le_sup_right :
      Submodule.span F₂ (populatedFiberUnion (presentationDefect p)) ≤
        geometricCapacitySpan (presentationDefect p))
    apply Submodule.subset_span
    let x : PopulatedPoint (presentationDefect p) :=
      ⟨⟨q, hqQ⟩, hq0, ⟨p i, hdec i, rfl⟩⟩
    exact ⟨x, hdec i, rfl⟩

/-- The entire finite presentation span lies in its geometric capacity span. -/
theorem decomposablePresentationSpan_le_geometricCapacitySpan {j : Nat}
    (p : Fin j → TwoForm) (hdec : ∀ i, IsDecomposableTwo (p i)) :
    decomposablePresentationSpan p ≤
      geometricCapacitySpan (presentationDefect p) := by
  apply Submodule.span_le.mpr
  rintro _ ⟨i, rfl⟩
  exact decomposable_mem_geometricCapacitySpan p hdec i

/-- Restrict the quotient projection to the presentation span. -/
def presentationProjection {j : Nat} (p : Fin j → TwoForm) :
    decomposablePresentationSpan p →ₗ[F₂] QuadraticQuotient :=
  quadraticQuotientProjection.domRestrict (decomposablePresentationSpan p)

theorem presentationProjection_range {j : Nat} (p : Fin j → TwoForm) :
    LinearMap.range (presentationProjection p) = presentationDefect p := by
  apply le_antisymm
  · rintro y ⟨x, rfl⟩
    change quadraticQuotientProjection x.1 ∈ presentationDefect p
    refine Submodule.span_induction (p := fun x _ =>
        quadraticQuotientProjection x ∈ presentationDefect p)
      ?_ ?_ ?_ ?_ x.2
    · rintro _ ⟨i, rfl⟩
      exact Submodule.subset_span ⟨i, rfl⟩
    · simp
    · intro u v _ _ hu hv
      simpa using (presentationDefect p).add_mem hu hv
    · intro a u _ hu
      simpa using (presentationDefect p).smul_mem a hu
  · apply Submodule.span_le.mpr
    rintro _ ⟨i, rfl⟩
    exact ⟨⟨p i, Submodule.subset_span ⟨i, rfl⟩⟩, rfl⟩

/-- When the presentation spans the target, the kernel of its quotient map is
exactly the target pulled back to the presentation span. -/
theorem presentationProjection_ker {j : Nat} (p : Fin j → TwoForm) :
    LinearMap.ker (presentationProjection p) =
      targetTwoSpace.comap (decomposablePresentationSpan p).subtype := by
  ext x
  simp [presentationProjection, quadraticQuotientProjection_eq_zero_iff]

/-- Manuscript Proposition 8.1 (capacity obstruction), specialized to
five-term multiplication.  A `j`-product decomposable presentation spanning
the target has quotient defect at most `j - 9`, and the capacity of that
defect is the full target dimension nine. -/
theorem capacity_obstruction {j : Nat} (p : Fin j → TwoForm)
    (hdec : ∀ i, IsDecomposableTwo (p i))
    (hT : targetTwoSpace ≤ decomposablePresentationSpan p) :
    Module.finrank F₂ (presentationDefect p) ≤ j - 9 ∧
      targetCapacity (presentationDefect p) = 9 := by
  let V := decomposablePresentationSpan p
  let Q := presentationDefect p
  let f := presentationProjection p
  have hker : LinearMap.ker f = targetTwoSpace.comap V.subtype := by
    exact presentationProjection_ker p
  have hkerRank : Module.finrank F₂ (LinearMap.ker f) = 9 := by
    rw [hker]
    calc
      Module.finrank F₂ (targetTwoSpace.comap V.subtype) =
          Module.finrank F₂ targetTwoSpace :=
        (Submodule.comapSubtypeEquivOfLe hT).finrank_eq
      _ = 9 := targetTwoSpace_finrank
  have hrange : LinearMap.range f = Q := presentationProjection_range p
  have hrank := f.finrank_range_add_finrank_ker
  rw [hrange, hkerRank] at hrank
  change Module.finrank F₂ Q + 9 = Module.finrank F₂ V at hrank
  have hVle : Module.finrank F₂ V ≤ j := by
    apply (finrank_span_le_card (Set.range p)).trans
    classical
    simpa using (Finset.card_image_le (s := Finset.univ) (f := p))
  have hdefect : Module.finrank F₂ Q ≤ j - 9 := by omega
  have hTgeo : targetTwoSpace ≤ geometricCapacitySpan Q :=
    hT.trans (decomposablePresentationSpan_le_geometricCapacitySpan p hdec)
  have hcap : targetCapacity Q = 9 := by
    rw [targetCapacity, defectCapacitySpan_eq_geometricCapacitySpan]
    have hinf : targetTwoSpace ⊓ geometricCapacitySpan Q = targetTwoSpace :=
      inf_eq_left.mpr hTgeo
    rw [hinf, targetTwoSpace_finrank]
  exact ⟨hdefect, hcap⟩

/-- Twelve decomposable quadratic products cannot span the five-term
multiplication target. -/
theorem no_twelve_decomposable_span (p : Fin 12 → TwoForm)
    (hdec : ∀ i, IsDecomposableTwo (p i)) :
    ¬ targetTwoSpace ≤ decomposablePresentationSpan p := by
  intro hT
  rcases capacity_obstruction p hdec hT with ⟨hQ, hcap⟩
  have hbound := targetCapacity_le_seven_of_finrank_le_three
    (presentationDefect p) (by simpa using hQ)
  omega

end

end N5
end UnrestrictedBooleanMul
