import UnrestrictedBooleanMul.N5.EnvelopeKernel
import UnrestrictedBooleanMul.N4.BooleanIdentities

/-!
# Independent cubic colours create a new high-degree direction

This module certifies manuscript Lemma 12.1, specifically the injectivity in
equation (12.2).  For the four normalized cubic colours, the six pairwise
products have an injective projection to six named quartic ANF coordinates.

The proof is an algebraic sparse-pivot calculation.  It does not enumerate
coefficient assignments.
-/

namespace UnrestrictedBooleanMul
namespace N5

noncomputable section

/-- The four normalized cubic colour directions from Section 12. -/
def colourDirection : Fin 4 → ANF 10 :=
  ![monomial ({0, 1, 5} : Finset (Fin 10)),
    monomial ({0, 5, 6} : Finset (Fin 10)),
    monomial ({0, 1, 6} : Finset (Fin 10)) +
      monomial ({0, 2, 5} : Finset (Fin 10)),
    monomial ({0, 5, 7} : Finset (Fin 10)) +
      monomial ({1, 5, 6} : Finset (Fin 10))]

/-- Cubic pivot coordinates separating the four displayed colours. -/
def colourCubicRow : Fin 4 → Finset (Fin 10) :=
  ![({0, 1, 5} : Finset (Fin 10)),
    ({0, 5, 6} : Finset (Fin 10)),
    ({0, 1, 6} : Finset (Fin 10)),
    ({0, 5, 7} : Finset (Fin 10))]

def colourCubicCoordinate (r : Fin 4) : ANF 10 →ₗ[F₂] F₂ where
  toFun p := p.coeff ⟨colourCubicRow r⟩
  map_add' p q := by simp
  map_smul' a p := by simp

/-- The selected cubic coefficient matrix is the identity. -/
theorem colourDirection_cubic_coefficient (r k : Fin 4) :
    colourCubicCoordinate r (colourDirection k) =
      if r = k then 1 else 0 := by
  fin_cases r <;> fin_cases k <;>
    simp (disch := decide) [colourCubicCoordinate, colourCubicRow,
      colourDirection, coeff_monomial] <;> decide

/-- The four normalized cubic colours in (12.1) are independent. -/
theorem colourDirection_linearIndependent :
    LinearIndependent F₂ colourDirection := by
  rw [Fintype.linearIndependent_iff]
  intro f hf i
  have hi := congrArg (colourCubicCoordinate i) hf
  rw [map_sum, map_zero] at hi
  simp only [map_smul, smul_eq_mul,
    colourDirection_cubic_coefficient] at hi
  rw [Finset.sum_eq_single i] at hi
  · simpa using hi
  · intro b _hb hbi
    simp [Ne.symm hbi]
  · simp

/-- The normalized cubic colour module `C₀`. -/
def colourSpace : Submodule F₂ (ANF 10) :=
  Submodule.span F₂ (Set.range colourDirection)

theorem colourSpace_finrank : Module.finrank F₂ colourSpace = 4 :=
  finrank_span_eq_card colourDirection_linearIndependent

/-- Coordinate reconstruction in the normalized cubic colour space. -/
def colourCombination : (Fin 4 → F₂) →ₗ[F₂] ANF 10 where
  toFun alpha := ∑ i : Fin 4, alpha i • colourDirection i
  map_add' alpha beta := by
    simp only [Pi.add_apply, add_smul, Finset.sum_add_distrib]
  map_smul' a alpha := by
    change (∑ i : Fin 4, (a * alpha i) • colourDirection i) =
      a • ∑ i : Fin 4, alpha i • colourDirection i
    rw [Finset.smul_sum]
    apply Finset.sum_congr rfl
    intro i _hi
    simp only [smul_smul]

/-- Left endpoint of the ordered pair list
`(c₁c₂,c₁c₃,c₁c₄,c₂c₃,c₂c₄,c₃c₄)`. -/
def colourPairLeft : Fin 6 → Fin 4 := ![0, 0, 0, 1, 1, 2]

/-- Right endpoint of the ordered pair list. -/
def colourPairRight : Fin 6 → Fin 4 := ![1, 2, 3, 2, 3, 3]

/-- Pluecker coordinates of the plane generated by two colour coefficient
vectors, in the same pair order as `colourPairLeft/Right`. -/
def colourPlaneCoeff (alpha beta : Fin 4 → F₂) : Fin 6 → F₂ :=
  fun k =>
    alpha (colourPairLeft k) * beta (colourPairRight k) +
    alpha (colourPairRight k) * beta (colourPairLeft k)

/-- Six quartic coordinates used to witness independent colour birth. -/
def colourQuarticRow : Fin 6 → Finset (Fin 10) :=
  ![({0, 1, 2, 5} : Finset (Fin 10)),
    ({0, 1, 5, 6} : Finset (Fin 10)),
    ({0, 2, 5, 6} : Finset (Fin 10)),
    ({0, 1, 5, 7} : Finset (Fin 10)),
    ({0, 2, 5, 7} : Finset (Fin 10)),
    ({0, 5, 6, 7} : Finset (Fin 10))]

/-- The sparse `6 × 6` coefficient matrix displayed in equation (12.2). -/
def colourBirthMatrix : Fin 6 → Fin 6 → F₂ :=
  ![![0, 1, 0, 0, 0, 0],
    ![1, 1, 1, 1, 1, 1],
    ![0, 0, 0, 1, 0, 0],
    ![0, 0, 1, 0, 0, 0],
    ![0, 0, 0, 0, 0, 1],
    ![0, 0, 0, 0, 1, 0]]

/-- Direct ANF verification of every entry of the manuscript matrix. -/
theorem colourBirth_product_coefficient (r k : Fin 6) :
    (colourDirection (colourPairLeft k) *
        colourDirection (colourPairRight k)).coeff
      ⟨colourQuarticRow r⟩ = colourBirthMatrix r k := by
  fin_cases r <;> fin_cases k <;>
    simp (disch := decide) [colourDirection, colourPairLeft, colourPairRight,
      colourQuarticRow, colourBirthMatrix, monomial_mul, coeff_monomial,
      add_mul, mul_add] <;> decide

/-- A linear combination of the six pairwise cubic-colour products. -/
def colourPairProductLinear : (Fin 6 → F₂) →ₗ[F₂] ANF 10 where
  toFun α := ∑ k : Fin 6, α k •
    (colourDirection (colourPairLeft k) *
      colourDirection (colourPairRight k))
  map_add' α β := by
    simp only [Pi.add_apply, add_smul, Finset.sum_add_distrib]
  map_smul' a α := by
    change (∑ k : Fin 6, (a * α k) •
      (colourDirection (colourPairLeft k) *
        colourDirection (colourPairRight k))) =
      a • ∑ k : Fin 6, α k •
        (colourDirection (colourPairLeft k) *
          colourDirection (colourPairRight k))
    rw [Finset.smul_sum]
    apply Finset.sum_congr rfl
    intro k _hk
    simp only [smul_smul]

/-- Projection to the six selected quartic ANF coordinates. -/
def colourQuarticProjection : ANF 10 →ₗ[F₂] (Fin 6 → F₂) where
  toFun p r := p.coeff ⟨colourQuarticRow r⟩
  map_add' p q := by
    ext r
    simp
  map_smul' a p := by
    ext r
    simp

/-- The selected high-degree projection of the colour-pair multiplication
map in equation (12.2). -/
def colourBirthMap : (Fin 6 → F₂) →ₗ[F₂] (Fin 6 → F₂) :=
  colourQuarticProjection.comp colourPairProductLinear

theorem colourBirthMap_apply (alpha : Fin 6 → F₂) (r : Fin 6) :
    colourBirthMap alpha r =
      ∑ k : Fin 6, alpha k * colourBirthMatrix r k := by
  change colourQuarticProjection
    (∑ k : Fin 6, alpha k •
      (colourDirection (colourPairLeft k) *
        colourDirection (colourPairRight k))) r = _
  rw [map_sum]
  simp only [Finset.sum_apply, map_smul, Pi.smul_apply, smul_eq_mul]
  apply Finset.sum_congr rfl
  intro k _hk
  exact congrArg (fun x => alpha k * x)
    (colourBirth_product_coefficient r k)

/-- The six selected quartic rows separate all six colour-pair products. -/
theorem colourBirthMap_ker_eq_bot : LinearMap.ker colourBirthMap = ⊥ := by
  apply le_antisymm
  · intro alpha halpha
    have hmap := (LinearMap.mem_ker).mp halpha
    have h1 : alpha 1 = 0 := by
      have h := congrFun hmap 0
      simpa [colourBirthMap_apply, colourBirthMatrix,
        Fin.sum_univ_succ] using h
    have h3 : alpha 3 = 0 := by
      have h := congrFun hmap 2
      simpa [colourBirthMap_apply, colourBirthMatrix,
        Fin.sum_univ_succ] using h
    have h2 : alpha 2 = 0 := by
      have h := congrFun hmap 3
      simpa [colourBirthMap_apply, colourBirthMatrix,
        Fin.sum_univ_succ] using h
    have h5 : alpha 5 = 0 := by
      have h := congrFun hmap 4
      simpa [colourBirthMap_apply, colourBirthMatrix,
        Fin.sum_univ_succ] using h
    have h4 : alpha 4 = 0 := by
      have h := congrFun hmap 5
      simpa [colourBirthMap_apply, colourBirthMatrix,
        Fin.sum_univ_succ] using h
    have h0 : alpha 0 = 0 := by
      have h := congrFun hmap 1
      simpa [colourBirthMap_apply, colourBirthMatrix,
        Fin.sum_univ_succ, h1, h2, h3, h4, h5] using h
    have halpha0 : alpha = 0 := by
      funext k
      fin_cases k <;> assumption
    simpa [halpha0]
  · exact bot_le

/-- Kernel-checked form of manuscript Lemma 12.1 / equation (12.2): six
independent pairwise cubic-colour products are born in high degree. -/
theorem independentColours_birth : Function.Injective colourBirthMap :=
  LinearMap.ker_eq_bot.mp colourBirthMap_ker_eq_bot

/-- Symmetric `4 × 4` form of one selected quartic coefficient on colour
products.  Its upper triangle is one row of `colourBirthMatrix`. -/
def colourDirectionProductMatrix (r : Fin 6) : Fin 4 → Fin 4 → F₂ :=
  ![![0, colourBirthMatrix r 0, colourBirthMatrix r 1,
        colourBirthMatrix r 2],
    ![colourBirthMatrix r 0, 0, colourBirthMatrix r 3,
        colourBirthMatrix r 4],
    ![colourBirthMatrix r 1, colourBirthMatrix r 3, 0,
        colourBirthMatrix r 5],
    ![colourBirthMatrix r 2, colourBirthMatrix r 4,
        colourBirthMatrix r 5, 0]]

/-- Every basis colour has zero selected quartic projection. -/
theorem colourDirection_quartic_zero (r : Fin 6) (i : Fin 4) :
    colourQuarticProjection (colourDirection i) r = 0 := by
  fin_cases r <;> fin_cases i <;>
    simp (disch := decide) [colourQuarticProjection, colourDirection,
      colourQuarticRow, coeff_monomial] <;> decide

/-- Coordinate table for all sixteen ordered products of basis colours. -/
theorem colourDirection_product_quartic_coefficient
    (r : Fin 6) (i j : Fin 4) :
    colourQuarticProjection (colourDirection i * colourDirection j) r =
      colourDirectionProductMatrix r i j := by
  fin_cases i <;> fin_cases j
  · simpa [N4.anf_mul_self, colourDirectionProductMatrix] using
      colourDirection_quartic_zero r 0
  · simpa [colourQuarticProjection, colourDirectionProductMatrix,
      colourPairLeft, colourPairRight] using
        colourBirth_product_coefficient r 0
  · simpa [colourQuarticProjection, colourDirectionProductMatrix,
      colourPairLeft, colourPairRight] using
        colourBirth_product_coefficient r 1
  · simpa [colourQuarticProjection, colourDirectionProductMatrix,
      colourPairLeft, colourPairRight] using
        colourBirth_product_coefficient r 2
  · have h := colourBirth_product_coefficient r 0
    simp [colourPairLeft, colourPairRight] at h
    rw [mul_comm (colourDirection 0) (colourDirection 1)] at h
    simpa [colourQuarticProjection, colourDirectionProductMatrix,
      colourPairLeft, colourPairRight] using h
  · simpa [N4.anf_mul_self, colourDirectionProductMatrix] using
      colourDirection_quartic_zero r 1
  · simpa [colourQuarticProjection, colourDirectionProductMatrix,
      colourPairLeft, colourPairRight] using
        colourBirth_product_coefficient r 3
  · simpa [colourQuarticProjection, colourDirectionProductMatrix,
      colourPairLeft, colourPairRight] using
        colourBirth_product_coefficient r 4
  · have h := colourBirth_product_coefficient r 1
    simp [colourPairLeft, colourPairRight] at h
    rw [mul_comm (colourDirection 0) (colourDirection 2)] at h
    simpa [colourQuarticProjection, colourDirectionProductMatrix,
      colourPairLeft, colourPairRight] using h
  · have h := colourBirth_product_coefficient r 3
    simp [colourPairLeft, colourPairRight] at h
    rw [mul_comm (colourDirection 1) (colourDirection 2)] at h
    simpa [colourQuarticProjection, colourDirectionProductMatrix,
      colourPairLeft, colourPairRight] using h
  · simpa [N4.anf_mul_self, colourDirectionProductMatrix] using
      colourDirection_quartic_zero r 2
  · simpa [colourQuarticProjection, colourDirectionProductMatrix,
      colourPairLeft, colourPairRight] using
        colourBirth_product_coefficient r 5
  · have h := colourBirth_product_coefficient r 2
    simp [colourPairLeft, colourPairRight] at h
    rw [mul_comm (colourDirection 0) (colourDirection 3)] at h
    simpa [colourQuarticProjection, colourDirectionProductMatrix,
      colourPairLeft, colourPairRight] using h
  · have h := colourBirth_product_coefficient r 4
    simp [colourPairLeft, colourPairRight] at h
    rw [mul_comm (colourDirection 1) (colourDirection 3)] at h
    simpa [colourQuarticProjection, colourDirectionProductMatrix,
      colourPairLeft, colourPairRight] using h
  · have h := colourBirth_product_coefficient r 5
    simp [colourPairLeft, colourPairRight] at h
    rw [mul_comm (colourDirection 2) (colourDirection 3)] at h
    simpa [colourQuarticProjection, colourDirectionProductMatrix,
      colourPairLeft, colourPairRight] using h
  · simpa [N4.anf_mul_self, colourDirectionProductMatrix] using
      colourDirection_quartic_zero r 3

/-- Expansion of an arbitrary colour product in one selected quartic row. -/
theorem colourQuarticProjection_product_combination_apply
    (alpha beta : Fin 4 → F₂) (r : Fin 6) :
    colourQuarticProjection (colourCombination alpha *
      colourCombination beta) r =
      ∑ i : Fin 4, ∑ j : Fin 4,
        alpha i * beta j * colourDirectionProductMatrix r i j := by
  change colourQuarticProjection
    ((∑ i : Fin 4, alpha i • colourDirection i) *
      (∑ j : Fin 4, beta j • colourDirection j)) r = _
  rw [Finset.sum_mul]
  simp_rw [Finset.mul_sum]
  rw [map_sum]
  simp only [Finset.sum_apply]
  apply Finset.sum_congr rfl
  intro i _hi
  rw [map_sum]
  simp only [Finset.sum_apply]
  apply Finset.sum_congr rfl
  intro j _hj
  rw [smul_mul_assoc, mul_smul_comm, map_smul, map_smul]
  simp only [Pi.smul_apply, smul_eq_mul,
    colourDirection_product_quartic_coefficient]
  ring

/-- Bilinear bridge from arbitrary colour coordinates to the six pairwise
products.  Diagonal terms are cubic by Boolean idempotence, so the selected
quartic projection is exactly the Pluecker combination. -/
theorem colourQuarticProjection_product_combination
    (alpha beta : Fin 4 → F₂) :
    colourQuarticProjection (colourCombination alpha *
      colourCombination beta) =
        colourBirthMap (colourPlaneCoeff alpha beta) := by
  ext r
  rw [colourQuarticProjection_product_combination_apply,
    colourBirthMap_apply]
  fin_cases r <;>
    simp [colourDirectionProductMatrix, colourBirthMatrix,
      colourPlaneCoeff, colourPairLeft, colourPairRight,
      Fin.sum_univ_succ] <;> ring

/-- Over `F₂`, vanishing Pluecker coordinates means that two coefficient
vectors are zero or equal. -/
theorem colourPlaneCoeff_eq_zero_iff_dependent
    (alpha beta : Fin 4 → F₂) :
    colourPlaneCoeff alpha beta = 0 ↔
      alpha = 0 ∨ beta = 0 ∨ alpha = beta := by
  constructor
  · intro hzero
    have h0 := congrFun hzero 0
    have h1 := congrFun hzero 1
    have h2 := congrFun hzero 2
    have h3 := congrFun hzero 3
    have h4 := congrFun hzero 4
    have h5 := congrFun hzero 5
    simp [colourPlaneCoeff, colourPairLeft, colourPairRight] at h0 h1 h2 h3 h4 h5
    apply N4.dependent_of_vectorWedge_zero alpha beta
    intro i j
    fin_cases i <;> fin_cases j <;>
      simp_all [CharTwo.add_self_eq_zero, add_comm]
    all_goals
      calc
        _ = alpha 0 * beta 1 + alpha 1 * beta 0 := add_comm _ _
        _ = 0 := h0
  · intro hdep
    rcases hdep with halpha | hbeta | heq
    · subst alpha
      funext k
      simp [colourPlaneCoeff]
    · subst beta
      funext k
      simp [colourPlaneCoeff]
    · subst beta
      funext k
      change alpha (colourPairLeft k) * alpha (colourPairRight k) +
        alpha (colourPairRight k) * alpha (colourPairLeft k) = (0 : F₂)
      rw [mul_comm (alpha (colourPairRight k))
        (alpha (colourPairLeft k)), CharTwo.add_self_eq_zero]

/-- Basis-free form of Lemma 12.1: the product of two independent colours
has a nonzero high-degree projection. -/
theorem independentColours_product_high_ne_zero
    (alpha beta : Fin 4 → F₂)
    (halpha : alpha ≠ 0) (hbeta : beta ≠ 0) (hne : alpha ≠ beta) :
    colourQuarticProjection (colourCombination alpha *
      colourCombination beta) ≠ 0 := by
  intro hzero
  have hbirth : colourBirthMap (colourPlaneCoeff alpha beta) =
      colourBirthMap 0 := by
    rw [← colourQuarticProjection_product_combination, hzero]
    exact (colourBirthMap.map_zero).symm
  have hplane := independentColours_birth hbirth
  rw [colourPlaneCoeff_eq_zero_iff_dependent] at hplane
  exact hplane.elim halpha (fun h => h.elim hbeta hne)

/-- The Boolean identities (12.5) used in the old-product-colour branch. -/
theorem colourProduct_tautologies (c d : ANF 10) :
    c * c = c ∧ d * d = d ∧
    c * (c * d) = c * d ∧ d * (c * d) = c * d ∧
    (c * d) * (c * d) = c * d := by
  constructor
  · exact N4.anf_mul_self c
  constructor
  · exact N4.anf_mul_self d
  constructor
  · exact N4.left_absorbs_product c d
  constructor
  · calc
      d * (c * d) = c * (d * d) := by ac_rfl
      _ = c * d := by rw [N4.anf_mul_self]
  · exact N4.anf_mul_self (c * d)

end
end N5
end UnrestrictedBooleanMul
