import UnrestrictedBooleanMul.N5.ColourBirth
import UnrestrictedBooleanMul.N4.BooleanIdentities

/-!
# Rank-one colour normalization

This module formalizes the rewiring and Boolean-absorption core of manuscript
Lemma 12.2.  If two gate factors carry only one nonzero colour, then one may
choose a nonzero-colour factor `U` and a zero-colour factor `c` without
changing the one-dimensional extension of the old wire space.  For their
product `F = Uc`, Boolean idempotence gives `UF = F` and `Fc = F`.
-/

namespace UnrestrictedBooleanMul
namespace N5

noncomputable section

/-- The three possibilities for two colours whose nonzero span is the line
generated by `g`, after excluding the both-zero case. -/
def RankOneColourPattern {H : Type*} [AddCommMonoid H] [Module F₂ H]
    (χ : ANF 10 →ₗ[F₂] H) (g : H) (X Y : ANF 10) : Prop :=
  (χ X = g ∧ χ Y = 0) ∨
  (χ X = 0 ∧ χ Y = g) ∨
  (χ X = g ∧ χ Y = g)

/-- Adding the old vector `X` to a new generator does not change the
one-dimensional extension of a subspace already containing `X`. -/
theorem sup_span_mul_add_eq_sup_span_mul
    (V : Submodule F₂ (ANF 10)) (X Y : ANF 10) (hX : X ∈ V) :
    V ⊔ Submodule.span F₂ ({X * (X + Y)} : Set (ANF 10)) =
      V ⊔ Submodule.span F₂ ({X * Y} : Set (ANF 10)) := by
  apply le_antisymm
  · apply sup_le le_sup_left
    rw [Submodule.span_le]
    rintro z (rfl : z = X * (X + Y))
    rw [mul_add, N4.anf_mul_self]
    exact Submodule.add_mem _
      ((le_sup_left : V ≤ _) hX)
      ((le_sup_right : Submodule.span F₂ ({X * Y} : Set (ANF 10)) ≤ _)
        (Submodule.mem_span_singleton_self (X * Y)))
  · apply sup_le le_sup_left
    rw [Submodule.span_le]
    rintro z (rfl : z = X * Y)
    have hsum : X + X * (X + Y) ∈
        V ⊔ Submodule.span F₂ ({X * (X + Y)} : Set (ANF 10)) :=
      Submodule.add_mem _
        ((le_sup_left : V ≤ _) hX)
        ((le_sup_right :
          Submodule.span F₂ ({X * (X + Y)} : Set (ANF 10)) ≤ _)
            (Submodule.mem_span_singleton_self (X * (X + Y))))
    have hcancel : X + X * (X + Y) = X * Y := by
      rw [mul_add, N4.anf_mul_self, ← add_assoc, anf_add_self, zero_add]
    rw [hcancel] at hsum
    exact hsum

/-- Manuscript Lemma 12.2, algebraic normalization form.  The conclusion
records membership of the normalized factors, their colours, equality of
the old and new wire extensions, and both identities in (12.4). -/
theorem rankOneColour_normalize
    {H : Type*} [AddCommMonoid H] [Module F₂ H]
    (V : Submodule F₂ (ANF 10)) (χ : ANF 10 →ₗ[F₂] H)
    (g : H) (X Y : ANF 10) (hX : X ∈ V) (hY : Y ∈ V)
    (hpattern : RankOneColourPattern χ g X Y) :
    ∃ U c : ANF 10,
      U ∈ V ∧ c ∈ V ∧ χ U = g ∧ χ c = 0 ∧
      V ⊔ Submodule.span F₂ ({U * c} : Set (ANF 10)) =
        V ⊔ Submodule.span F₂ ({X * Y} : Set (ANF 10)) ∧
      U * (U * c) = U * c ∧ (U * c) * c = U * c := by
  rcases hpattern with hXY | hYX | hsame
  · refine ⟨X, Y, hX, hY, hXY.1, hXY.2, rfl,
      N4.left_absorbs_product X Y, N4.right_absorbs_product X Y⟩
  · refine ⟨Y, X, hY, hX, hYX.2, hYX.1, ?_,
      N4.left_absorbs_product Y X, N4.right_absorbs_product Y X⟩
    rw [mul_comm]
  · let c := X + Y
    have hcV : c ∈ V := V.add_mem hX hY
    have hcolour : χ c = 0 := by
      change χ (X + Y) = 0
      rw [map_add, hsame.1, hsame.2]
      calc
        g + g = (1 : F₂) • g + (1 : F₂) • g := by simp
        _ = ((1 : F₂) + 1) • g := by rw [add_smul]
        _ = 0 := by rw [CharTwo.add_self_eq_zero, zero_smul]
    refine ⟨X, c, hX, hcV, hsame.1, hcolour, ?_,
      N4.left_absorbs_product X c, N4.right_absorbs_product X c⟩
    exact sup_span_mul_add_eq_sup_span_mul V X Y hX

end
end N5
end UnrestrictedBooleanMul
