import UnrestrictedBooleanMul.N5.LineSecantGifts

/-!
# Fano-line incidence pivots

The local secant certificates bound the quotient span of every populated
Fano-line gift through a represented point.  This module records the exact
lightweight interface needed from the remaining Fano-plane incidence
argument: the full relation-gift range is contained in those line gifts plus
one residual direction.  Under that algebraic codimension-one statement, the
sharp one-place gift bounds follow immediately.

No finite atlas is enumerated here.  The eventual incidence theorem can be
proved solely in the relation kernel and then supplied through
`RelationGiftRangeGeneratedByLinesAndOne`.
-/

namespace UnrestrictedBooleanMul
namespace N5

noncomputable section

/-- Fano-line gifts through `x`, after quotienting by all intrinsic local
displacements. -/
def fanoLineGiftQuotientSpaceThrough
    (Q : Submodule F₂ QuadraticQuotient) (x : PopulatedPoint Q) :
    Submodule F₂ (TargetCoeff ⧸ localDisplacementCoeffSpace Q) :=
  LinearMap.range
    ((Submodule.mkQ (localDisplacementCoeffSpace Q)).domRestrict
      (fanoLineGiftCoeffSpaceThrough Q x))

/-- Algebraic form of the remaining pointed Fano-incidence statement: modulo
intrinsic displacement, all relation gifts are generated by line gifts
through `x` and at most one residual (quadrilateral) direction. -/
def RelationGiftRangeGeneratedByLinesAndOne
    (Q : Submodule F₂ QuadraticQuotient) (x : PopulatedPoint Q) : Prop :=
  ∃ v : TargetCoeff ⧸ localDisplacementCoeffSpace Q,
    LinearMap.range (defectRelationCoeffMap Q) ≤
      fanoLineGiftQuotientSpaceThrough Q x ⊔
        Submodule.span F₂ {v}

/-- Adding one vector to a finite-dimensional subspace raises its dimension
by at most one. -/
theorem finrank_le_add_one_of_le_sup_span_singleton
    {V : Type*} [AddCommGroup V] [Module F₂ V] [Module.Finite F₂ V]
    (S T : Submodule F₂ V) (v : V)
    (h : S ≤ T ⊔ Submodule.span F₂ {v}) :
    Module.finrank F₂ S ≤ Module.finrank F₂ T + 1 := by
  calc
    Module.finrank F₂ S ≤
        Module.finrank F₂ ↑(T ⊔ Submodule.span F₂ {v}) :=
      Submodule.finrank_mono h
    _ ≤ Module.finrank F₂ T +
        Module.finrank F₂ (Submodule.span F₂ {v}) :=
      Submodule.finrank_add_le_finrank_add_finrank T
        (Submodule.span F₂ {v})
    _ ≤ Module.finrank F₂ T + 1 := by
      apply Nat.add_le_add_left
      simpa using (finrank_span_le_card ({v} : Set V))

/-- The pointed incidence condition converts a line-gift quotient bound into
a bound one dimension larger for the entire relation-gift range. -/
theorem relationGiftRank_le_lineQuotientRank_add_one
    (Q : Submodule F₂ QuadraticQuotient) (x : PopulatedPoint Q)
    (hinc : RelationGiftRangeGeneratedByLinesAndOne Q x) :
    relationGiftRank Q ≤
      Module.finrank F₂ (fanoLineGiftQuotientSpaceThrough Q x) + 1 := by
  rcases hinc with ⟨v, hv⟩
  rw [relationGiftRank_eq_coefficients]
  exact finrank_le_add_one_of_le_sup_span_singleton
    (LinearMap.range (defectRelationCoeffMap Q))
    (fanoLineGiftQuotientSpaceThrough Q x) v hv

/-- Sharp rational one-place row, conditional only on the pointed algebraic
Fano-incidence statement. -/
theorem relationGiftRank_le_three_of_rationalZero_incidence
    (Q : Submodule F₂ QuadraticQuotient) (x : PopulatedPoint Q)
    (q : LocalKleinParam) (hq : RationalLocalEffective q)
    (hxPoint : populatedQuotientPoint x =
      closedPlaceQuotientPoint 0 q)
    (hzero : IsRepresentedPlace Q 0)
    (hinc : RelationGiftRangeGeneratedByLinesAndOne Q x) :
    relationGiftRank Q ≤ 3 := by
  have hline : Module.finrank F₂
      (fanoLineGiftQuotientSpaceThrough Q x) ≤ 2 :=
    fanoLineGiftCoeffSpaceThrough_rationalZero_quotientRank_le_two
      Q x q hq hxPoint hzero
  have hgift := relationGiftRank_le_lineQuotientRank_add_one Q x hinc
  omega

/-- Sharp degree-two one-place row, conditional only on the pointed
algebraic Fano-incidence statement. -/
theorem relationGiftRank_le_two_of_degreeTwo_incidence
    (Q : Submodule F₂ QuadraticQuotient) (x : PopulatedPoint Q)
    (q : LocalKleinParam) (hq : DegreeTwoLocalEffective q)
    (hxPoint : populatedQuotientPoint x =
      closedPlaceQuotientPoint 3 q)
    (hdegree : IsRepresentedPlace Q 3)
    (hinc : RelationGiftRangeGeneratedByLinesAndOne Q x) :
    relationGiftRank Q ≤ 2 := by
  have hline : Module.finrank F₂
      (fanoLineGiftQuotientSpaceThrough Q x) ≤ 1 :=
    fanoLineGiftCoeffSpaceThrough_degreeTwo_quotientRank_le_one
      Q x q hq hxPoint hdegree
  have hgift := relationGiftRank_le_lineQuotientRank_add_one Q x hinc
  omega

end

end N5
end UnrestrictedBooleanMul
