import UnrestrictedBooleanMul.N5.LowDefectAnchor
import UnrestrictedBooleanMul.N5.TargetCleanMatrix
import UnrestrictedBooleanMul.N5.SuffixBudget
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas

/-!
# Canonical first-order states with one decomposable anchor

Every low-defect all-quadratic prefix is dominated by a canonical state
whose quadratic image is `U + <q>` for one decomposable form `q`.  The
target-clean intersection theorem shows that this state still has exactly
the eight-dimensional first-order target part.  Its defect is precisely the
dimension of the quotient line generated by `q`, so replacing the circuit
prefix by this state preserves defect and therefore preserves legal suffixes.
-/

namespace UnrestrictedBooleanMul
namespace N5

noncomputable section

def firstOrderAnchorTwoSpace (q : TwoForm) : Submodule F₂ TwoForm :=
  firstOrderEnvelopeTwoSpace ⊔
    Submodule.span F₂ ({q} : Set TwoForm)

def firstOrderAnchorState (q : TwoForm) : Submodule F₂ (ANF 10) :=
  E2.quadraticEnvelopeState (firstOrderAnchorTwoSpace q)

theorem firstOrderEnvelopeState_le_firstOrderAnchorState
    (q : TwoForm) :
    firstOrderEnvelopeState ≤ firstOrderAnchorState q := by
  intro p hp
  have hpData := (E2.mem_quadraticEnvelopeState_iff
    firstOrderEnvelopeTwoSpace p).1 hp
  exact (E2.mem_quadraticEnvelopeState_iff
    (firstOrderAnchorTwoSpace q) p).2
    ⟨hpData.1, Submodule.mem_sup_left hpData.2⟩

theorem targetTwoSpace_inf_firstOrderAnchorTwoSpace
    (q : TwoForm) (hqdec : IsDecomposableTwo q) :
    targetTwoSpace ⊓ firstOrderAnchorTwoSpace q =
      firstOrderEnvelopeTwoSpace := by
  have hfirstClean : firstOrderEnvelopeTwoSpace ≤
      targetCleanSecondJetSpace :=
    (le_sup_left : firstOrderEnvelopeTwoSpace ≤
      firstOrderEnvelopeTwoSpace ⊔ quadraticExterior secondJetCoreSpace).trans
      (le_sup_left :
        firstOrderEnvelopeTwoSpace ⊔ quadraticExterior secondJetCoreSpace ≤
          targetCleanSecondJetSpace)
  apply le_antisymm
  · rintro p ⟨hpT, hp⟩
    have hpClean : p ∈ targetCleanSecondJetSpace ⊔
        Submodule.span F₂ ({q} : Set TwoForm) := by
      exact (sup_le_sup_right hfirstClean
        (Submodule.span F₂ ({q} : Set TwoForm))) hp
    have hpInf : p ∈ targetTwoSpace ⊓
        (targetCleanSecondJetSpace ⊔
          Submodule.span F₂ ({q} : Set TwoForm)) := ⟨hpT, hpClean⟩
    rwa [targetTwoSpace_inf_targetClean_sup_decomposable q hqdec] at hpInf
  · intro p hp
    exact ⟨firstOrderEnvelopeTwoSpace_le_targetTwoSpace hp,
      Submodule.mem_sup_left hp⟩

/-- The canonical anchored two-form space lies in the target-clean second
jet module plus its single decomposable anchor. -/
theorem firstOrderAnchorTwoSpace_le_targetClean_sup_anchor
    (q : TwoForm) :
    firstOrderAnchorTwoSpace q ≤
      targetCleanSecondJetSpace ⊔
        Submodule.span F₂ ({q} : Set TwoForm) := by
  apply sup_le
  · exact ((le_sup_left : firstOrderEnvelopeTwoSpace ≤
        firstOrderEnvelopeTwoSpace ⊔ quadraticExterior secondJetCoreSpace).trans
      (le_sup_left :
        firstOrderEnvelopeTwoSpace ⊔ quadraticExterior secondJetCoreSpace ≤
          targetCleanSecondJetSpace)).trans le_sup_left
  · exact le_sup_right

/-- Every quadratic word in the canonical anchored base has precisely the
target-clean-plus-anchor quadratic localization used in the rank-one branch. -/
theorem quadraticProjection_mem_targetClean_sup_anchor_of_mem_anchorState
    (q : TwoForm) {c : ANF 10} (hc : c ∈ firstOrderAnchorState q) :
    quadraticProjection 10 c ∈
      targetCleanSecondJetSpace ⊔
        Submodule.span F₂ ({q} : Set TwoForm) := by
  have hcTwo : quadraticProjection 10 c ∈ firstOrderAnchorTwoSpace q :=
    ((E2.mem_quadraticEnvelopeState_iff
      (firstOrderAnchorTwoSpace q) c).1 hc).2
  exact firstOrderAnchorTwoSpace_le_targetClean_sup_anchor q hcTwo

theorem firstOrderAnchorTwoSpace_finrank_of_mem_target
    (q : TwoForm) (hqdec : IsDecomposableTwo q)
    (hqT : q ∈ targetTwoSpace) :
    Module.finrank F₂ (firstOrderAnchorTwoSpace q) = 8 := by
  have hqU : q ∈ firstOrderEnvelopeTwoSpace := by
    have hqInf : q ∈ targetTwoSpace ⊓ firstOrderAnchorTwoSpace q :=
      ⟨hqT, Submodule.mem_sup_right
        (Submodule.mem_span_singleton_self q)⟩
    rwa [targetTwoSpace_inf_firstOrderAnchorTwoSpace q hqdec] at hqInf
  have hspan : Submodule.span F₂ ({q} : Set TwoForm) ≤
      firstOrderEnvelopeTwoSpace := by
    rw [Submodule.span_le]
    simpa using hqU
  rw [firstOrderAnchorTwoSpace, sup_eq_left.mpr hspan,
    firstOrderEnvelopeTwoSpace_finrank]

/-- A decomposable anchor which is itself target-valued already belongs to
the first-order envelope, so adjoining it changes neither two-form space nor
ANF state. -/
theorem firstOrderAnchorTwoSpace_eq_firstOrderEnvelope_of_mem_target
    (q : TwoForm) (hqdec : IsDecomposableTwo q)
    (hqT : q ∈ targetTwoSpace) :
    firstOrderAnchorTwoSpace q = firstOrderEnvelopeTwoSpace := by
  have hqU : q ∈ firstOrderEnvelopeTwoSpace := by
    have hqInf : q ∈ targetTwoSpace ⊓ firstOrderAnchorTwoSpace q :=
      ⟨hqT, Submodule.mem_sup_right
        (Submodule.mem_span_singleton_self q)⟩
    rwa [targetTwoSpace_inf_firstOrderAnchorTwoSpace q hqdec] at hqInf
  apply sup_eq_left.mpr
  rw [Submodule.span_le]
  simpa using hqU

theorem firstOrderAnchorState_eq_firstOrderEnvelope_of_mem_target
    (q : TwoForm) (hqdec : IsDecomposableTwo q)
    (hqT : q ∈ targetTwoSpace) :
    firstOrderAnchorState q = firstOrderEnvelopeState := by
  rw [firstOrderAnchorState, firstOrderEnvelopeState,
    firstOrderAnchorTwoSpace_eq_firstOrderEnvelope_of_mem_target
      q hqdec hqT]

theorem firstOrderAnchorTwoSpace_finrank_of_not_mem_target
    (q : TwoForm) (hqT : q ∉ targetTwoSpace) :
    Module.finrank F₂ (firstOrderAnchorTwoSpace q) = 9 := by
  have hqU : q ∉ firstOrderEnvelopeTwoSpace :=
    fun h => hqT (firstOrderEnvelopeTwoSpace_le_targetTwoSpace h)
  rw [firstOrderAnchorTwoSpace,
    Submodule.finrank_sup_span_singleton hqU,
    firstOrderEnvelopeTwoSpace_finrank]

theorem firstOrderAnchorState_targetRank
    (q : TwoForm) (hqdec : IsDecomposableTwo q) :
    N4.flagTargetRank (firstOrderAnchorState q) (mulTarget 5) = 8 := by
  rw [firstOrderAnchorState, E2.quadraticEnvelopeState_targetRank,
    inf_comm, targetTwoSpace_inf_firstOrderAnchorTwoSpace q hqdec,
    firstOrderEnvelopeTwoSpace_finrank]

/-- The target part of a canonical anchored state is exactly contained in the
first-order target envelope; the adjoined decomposable direction contributes
only quotient defect. -/
theorem firstOrderAnchorState_inf_targetAmbient_le_firstOrderEnvelopeState
    (q : TwoForm) (hqdec : IsDecomposableTwo q) :
    firstOrderAnchorState q ⊓ N4.targetAmbient 10 (mulTarget 5) ≤
      firstOrderEnvelopeState := by
  intro p hp
  have htwo : quadraticProjection 10 p ∈
      targetTwoSpace ⊓ firstOrderAnchorTwoSpace q := by
    refine ⟨quadraticProjection_mem_targetTwoSpace_of_mem_targetAmbient
        hp.2, ?_⟩
    exact ((E2.mem_quadraticEnvelopeState_iff
      (firstOrderAnchorTwoSpace q) p).1 hp.1).2
  rw [targetTwoSpace_inf_firstOrderAnchorTwoSpace q hqdec] at htwo
  exact (E2.mem_quadraticEnvelopeState_iff
    firstOrderEnvelopeTwoSpace p).2
    ⟨targetAmbient_five_le_quadraticANFSpace hp.2, htwo⟩

theorem firstOrderAnchorState_defectRank_of_mem_target
    (q : TwoForm) (hqdec : IsDecomposableTwo q)
    (hqT : q ∈ targetTwoSpace) :
    N4.flagDefectRank (firstOrderAnchorState q) (mulTarget 5) = 0 := by
  rw [firstOrderAnchorState, E2.quadraticEnvelopeState_defectRank,
    firstOrderAnchorTwoSpace_finrank_of_mem_target q hqdec hqT, inf_comm,
    targetTwoSpace_inf_firstOrderAnchorTwoSpace q hqdec,
    firstOrderEnvelopeTwoSpace_finrank]

theorem firstOrderAnchorState_defectRank_of_not_mem_target
    (q : TwoForm) (hqdec : IsDecomposableTwo q)
    (hqT : q ∉ targetTwoSpace) :
    N4.flagDefectRank (firstOrderAnchorState q) (mulTarget 5) = 1 := by
  rw [firstOrderAnchorState, E2.quadraticEnvelopeState_defectRank,
    firstOrderAnchorTwoSpace_finrank_of_not_mem_target q hqT, inf_comm,
    targetTwoSpace_inf_firstOrderAnchorTwoSpace q hqdec,
    firstOrderEnvelopeTwoSpace_finrank]

theorem firstOrderAnchorState_defectRank_eq_quotientSpan
    (q : TwoForm) (hqdec : IsDecomposableTwo q) :
    N4.flagDefectRank (firstOrderAnchorState q) (mulTarget 5) =
      Module.finrank F₂ (Submodule.span F₂
        ({quadraticQuotientProjection q} : Set QuadraticQuotient)) := by
  classical
  by_cases hqT : q ∈ targetTwoSpace
  · have hzero : quadraticQuotientProjection q = 0 :=
      (quadraticQuotientProjection_eq_zero_iff q).2 hqT
    rw [firstOrderAnchorState_defectRank_of_mem_target q hqdec hqT,
      hzero]
    rw [Submodule.span_zero_singleton, finrank_bot]
  · have hne : quadraticQuotientProjection q ≠ 0 := by
      intro hzero
      exact hqT ((quadraticQuotientProjection_eq_zero_iff q).1 hzero)
    rw [firstOrderAnchorState_defectRank_of_not_mem_target q hqdec hqT,
      finrank_span_singleton hne]

theorem circuitFlag_le_firstOrderAnchorState
    {r j : Nat} (C : Circuit 10 r)
    (hall : AllQuadraticPrefix C j) (q : TwoForm)
    (hcover : quadraticPrefixImage C j ≤ firstOrderAnchorTwoSpace q) :
    N4.circuitFlag C j ≤ firstOrderAnchorState q := by
  exact circuitFlag_le_quadraticEnvelopeState_of_allQuadratic
    C hall (firstOrderAnchorTwoSpace q) hcover

/-- A low-defect all-quadratic prefix is dominated by a canonical anchored
state of exactly the same target defect. -/
theorem exists_equalDefect_firstOrderAnchorState
    {r j : Nat} (C : Circuit 10 r) (hj : j ≤ r)
    (hall : AllQuadraticPrefix C j)
    (hdef : N4.flagDefectRank (N4.circuitFlag C j) (mulTarget 5) ≤ 1) :
    ∃ q : TwoForm,
      IsDecomposableTwo q ∧
      N4.circuitFlag C j ≤ firstOrderAnchorState q ∧
      N4.flagDefectRank (firstOrderAnchorState q) (mulTarget 5) =
        N4.flagDefectRank (N4.circuitFlag C j) (mulTarget 5) := by
  let hflat := quadraticPrefixFlattening_of_all_quadratic C hj hall
  have hpresentation : Module.finrank F₂
      (presentationDefect hflat.generator) ≤ 1 := by
    rw [quadraticPrefixFlattening_defect_eq_flagDefect C hflat hall]
    exact hdef
  rcases exists_decomposable_anchor_of_quadraticPrefix C hflat
      hpresentation with
    ⟨q, hqdec, hq, hprincipal, htargetCover⟩
  have htarget : N4.circuitFlag C j ⊓
      N4.targetAmbient 10 (mulTarget 5) ≤ firstOrderEnvelopeState :=
    allQuadraticPrefix_target_le_firstOrder_of_flagDefect_le_one
      C hflat hall hdef
  have hcover : quadraticPrefixImage C j ≤ firstOrderAnchorTwoSpace q :=
    quadraticPrefixImage_le_firstOrder_sup_anchor
      C hall htarget q hq htargetCover
  refine ⟨q, hqdec,
    circuitFlag_le_firstOrderAnchorState C hall q hcover, ?_⟩
  rw [firstOrderAnchorState_defectRank_eq_quotientSpan q hqdec,
    ← hprincipal,
    quadraticPrefixFlattening_defect_eq_flagDefect C hflat hall]

/-- Stable target containment transfers from a dominating state of equal
defect by the already checked equal-defect suffix simulation. -/
theorem stableTargetSubspace_of_dominated_equalDefect
    {W A U : Submodule F₂ (ANF 10)}
    (hsub : W ≤ A)
    (hdef : N4.flagDefectRank W (mulTarget 5) =
      N4.flagDefectRank A (mulTarget 5))
    (hAdef : N4.flagDefectRank A (mulTarget 5) ≤ 3)
    (hstable : StableTargetSubspace A U) :
    StableTargetSubspace W U := by
  intro V hreach
  have hsim : DefectLegalSuffix A (A ⊔ V) :=
    hreach.simulate_from_equal_defect hsub hdef hAdef
  intro p hp
  exact hstable (A ⊔ V) hsim
    ⟨Submodule.mem_sup_right hp.1, hp.2⟩

/-- The remaining first-order problem can be stated entirely for the
canonical anchored states. -/
def AnchoredFirstOrderStability : Prop :=
  ∀ q : TwoForm, IsDecomposableTwo q →
    StableTargetSubspace (firstOrderAnchorState q) firstOrderEnvelopeState

theorem stableFirstOrderPrefix_of_anchored
    (hstable : AnchoredFirstOrderStability)
    {r j : Nat} (C : Circuit 10 r) (hj : j ≤ r)
    (hall : AllQuadraticPrefix C j)
    (hdef : N4.flagDefectRank (N4.circuitFlag C j) (mulTarget 5) ≤ 1) :
    StableTargetSubspace (N4.circuitFlag C j) firstOrderEnvelopeState := by
  rcases exists_equalDefect_firstOrderAnchorState C hj hall hdef with
    ⟨q, hqdec, hsub, hdefeq⟩
  apply stableTargetSubspace_of_dominated_equalDefect
    hsub hdefeq.symm (by rw [hdefeq]; exact hdef.trans (by omega))
  exact hstable q hqdec

end
end N5
end UnrestrictedBooleanMul
