import UnrestrictedBooleanMul.N5.QuadraticPrefixExact
import Mathlib.LinearAlgebra.FiniteDimensional.Basic

/-!
# A decomposable anchor for a low-defect quadratic prefix

A one-dimensional presentation defect is generated by the quotient class of
one of the presentation's actual decomposable generators.  Consequently the
entire quadratic presentation lies in the multiplication target plus the
span of that one generator.  This is the algebraic source of the optional
`<q>` term in the target-clean second-jet argument.
-/

namespace UnrestrictedBooleanMul
namespace N5

noncomputable section

/-- A finite decomposable presentation of quotient defect at most one has an
actual decomposable anchor modulo the Hankel target. -/
theorem exists_decomposable_anchor_of_presentationDefect_le_one
    {j : Nat} (p : Fin j → TwoForm)
    (hdec : ∀ i, IsDecomposableTwo (p i))
    (hdef : Module.finrank F₂ (presentationDefect p) ≤ 1) :
    ∃ q : TwoForm,
      IsDecomposableTwo q ∧
      q ∈ decomposablePresentationSpan p ∧
      decomposablePresentationSpan p ≤
        targetTwoSpace ⊔ Submodule.span F₂ ({q} : Set TwoForm) := by
  classical
  by_cases hQ : presentationDefect p = ⊥
  · refine ⟨0, decomposableTwo_zero, Submodule.zero_mem _, ?_⟩
    intro x hx
    have hprojection : quadraticQuotientProjection x ∈
        presentationDefect p := by
      rw [← presentationProjection_range p]
      exact ⟨⟨x, hx⟩, rfl⟩
    rw [hQ] at hprojection
    have hzero : quadraticQuotientProjection x = 0 := by
      simpa using hprojection
    exact Submodule.mem_sup_left
      ((quadraticQuotientProjection_eq_zero_iff x).1 hzero)
  · have hexists : ∃ i : Fin j,
        quadraticQuotientProjection (p i) ≠ 0 := by
      by_contra hnone
      have hall : ∀ i : Fin j,
          quadraticQuotientProjection (p i) = 0 := by
        intro i
        by_contra hi
        exact hnone ⟨i, hi⟩
      apply hQ
      apply le_antisymm
      · rw [presentationDefect, Submodule.span_le]
        rintro _ ⟨i, rfl⟩
        change quadraticQuotientProjection (p i) ∈ (⊥ :
          Submodule F₂ QuadraticQuotient)
        rw [hall i]
        exact Submodule.zero_mem _
      · exact bot_le
    rcases hexists with ⟨i, hi⟩
    let q := p i
    have hqQ : quadraticQuotientProjection q ∈
        presentationDefect p := by
      apply Submodule.subset_span
      exact ⟨i, rfl⟩
    have hdimNe : Module.finrank F₂ (presentationDefect p) ≠ 0 := by
      intro hzero
      apply hQ
      exact Submodule.finrank_eq_zero.mp hzero
    have hdim : Module.finrank F₂ (presentationDefect p) = 1 := by
      omega
    have hprincipal : presentationDefect p =
        Submodule.span F₂ ({quadraticQuotientProjection q} :
          Set QuadraticQuotient) :=
      (Submodule.eq_of_le_of_finrank_eq
        (Submodule.span_le.mpr (by simpa using hqQ))
        (by rw [finrank_span_singleton hi, hdim])).symm
    refine ⟨q, hdec i, ?_, ?_⟩
    · exact Submodule.subset_span ⟨i, rfl⟩
    · intro x hx
      have hxQ : quadraticQuotientProjection x ∈
          presentationDefect p := by
        rw [← presentationProjection_range p]
        exact ⟨⟨x, hx⟩, rfl⟩
      rw [hprincipal] at hxQ
      rcases Submodule.mem_span_singleton.mp hxQ with ⟨a, ha⟩
      let y := x - a • q
      have hyTarget : y ∈ targetTwoSpace := by
        apply (quadraticQuotientProjection_eq_zero_iff y).1
        simp only [y, map_sub, map_smul, ha]
        exact sub_self _
      have haq : a • q ∈ Submodule.span F₂ ({q} : Set TwoForm) :=
        Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self q)
      have hsum := (targetTwoSpace ⊔
          Submodule.span F₂ ({q} : Set TwoForm)).add_mem
        (Submodule.mem_sup_left hyTarget) (Submodule.mem_sup_right haq)
      simpa only [y, sub_add_cancel] using hsum

/-- Circuit-facing form: the quadratic image of a flattened all-quadratic
prefix of defect at most one has a decomposable anchor modulo the target. -/
theorem exists_decomposable_anchor_of_quadraticPrefix
    {r j : Nat} (C : Circuit 10 r)
    (hflat : QuadraticPrefixFlattening C j)
    (hdef : Module.finrank F₂
      (presentationDefect hflat.generator) ≤ 1) :
    ∃ q : TwoForm,
      IsDecomposableTwo q ∧ q ∈ quadraticPrefixImage C j ∧
      quadraticPrefixImage C j ≤
        targetTwoSpace ⊔ Submodule.span F₂ ({q} : Set TwoForm) := by
  rcases exists_decomposable_anchor_of_presentationDefect_le_one
      hflat.generator hflat.decomposable hdef with
    ⟨q, hqdec, hq, hspan⟩
  rw [hflat.span_eq] at hq hspan
  exact ⟨q, hqdec, hq, hspan⟩

end
end N5
end UnrestrictedBooleanMul
