import UnrestrictedBooleanMul.N5.LowDefectPrefix
import Mathlib.LinearAlgebra.FiniteDimensional.Basic

/-!
# A decomposable anchor for a low-defect quadratic prefix

A one-dimensional presentation defect is generated by the quotient class of
one of the presentation's actual decomposable generators.  Consequently the
entire quadratic presentation lies in the multiplication target plus the
span of that one generator.  This is the algebraic source of the optional
`<q>` term in the target-clean second-jet argument.
-/

namespace UnrestrictedBooleanMul
namespace N5

noncomputable section

/-- A finite decomposable presentation of quotient defect at most one has an
actual decomposable anchor modulo the Hankel target. -/
theorem exists_decomposable_anchor_of_presentationDefect_le_one
    {j : Nat} (p : Fin j → TwoForm)
    (hdec : ∀ i, IsDecomposableTwo (p i))
    (hdef : Module.finrank F₂ (presentationDefect p) ≤ 1) :
    ∃ q : TwoForm,
      IsDecomposableTwo q ∧
      q ∈ decomposablePresentationSpan p ∧
      presentationDefect p = Submodule.span F₂
        ({quadraticQuotientProjection q} : Set QuadraticQuotient) ∧
      decomposablePresentationSpan p ≤
        targetTwoSpace ⊔ Submodule.span F₂ ({q} : Set TwoForm) := by
  classical
  by_cases hQ : presentationDefect p = ⊥
  · refine ⟨0, decomposableTwo_zero, Submodule.zero_mem _, ?_, ?_⟩
    · simpa using hQ
    intro x hx
    have hprojection : quadraticQuotientProjection x ∈
        presentationDefect p := by
      rw [← presentationProjection_range p]
      exact ⟨⟨x, hx⟩, rfl⟩
    rw [hQ] at hprojection
    have hzero : quadraticQuotientProjection x = 0 := by
      simpa using hprojection
    exact Submodule.mem_sup_left
      ((quadraticQuotientProjection_eq_zero_iff x).1 hzero)
  · have hexists : ∃ i : Fin j,
        quadraticQuotientProjection (p i) ≠ 0 := by
      by_contra hnone
      have hall : ∀ i : Fin j,
          quadraticQuotientProjection (p i) = 0 := by
        intro i
        by_contra hi
        exact hnone ⟨i, hi⟩
      apply hQ
      apply le_antisymm
      · rw [presentationDefect, Submodule.span_le]
        rintro _ ⟨i, rfl⟩
        change quadraticQuotientProjection (p i) ∈ (⊥ :
          Submodule F₂ QuadraticQuotient)
        rw [hall i]
        exact Submodule.zero_mem _
      · exact bot_le
    rcases hexists with ⟨i, hi⟩
    let q := p i
    have hqQ : quadraticQuotientProjection q ∈
        presentationDefect p := by
      apply Submodule.subset_span
      exact ⟨i, rfl⟩
    have hdimNe : Module.finrank F₂ (presentationDefect p) ≠ 0 := by
      intro hzero
      apply hQ
      exact Submodule.finrank_eq_zero.mp hzero
    have hdim : Module.finrank F₂ (presentationDefect p) = 1 := by
      omega
    have hprincipal : presentationDefect p =
        Submodule.span F₂ ({quadraticQuotientProjection q} :
          Set QuadraticQuotient) :=
      (Submodule.eq_of_le_of_finrank_eq
        (Submodule.span_le.mpr (by simpa using hqQ))
        (by rw [finrank_span_singleton hi, hdim])).symm
    refine ⟨q, hdec i, ?_, hprincipal, ?_⟩
    · exact Submodule.subset_span ⟨i, rfl⟩
    · intro x hx
      have hxQ : quadraticQuotientProjection x ∈
          presentationDefect p := by
        rw [← presentationProjection_range p]
        exact ⟨⟨x, hx⟩, rfl⟩
      rw [hprincipal] at hxQ
      rcases Submodule.mem_span_singleton.mp hxQ with ⟨a, ha⟩
      let y := x - a • q
      have hyTarget : y ∈ targetTwoSpace := by
        apply (quadraticQuotientProjection_eq_zero_iff y).1
        simp only [y, map_sub, map_smul, ha]
        exact sub_self _
      have haq : a • q ∈ Submodule.span F₂ ({q} : Set TwoForm) :=
        Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self q)
      have hsum := (targetTwoSpace ⊔
          Submodule.span F₂ ({q} : Set TwoForm)).add_mem
        (Submodule.mem_sup_left hyTarget) (Submodule.mem_sup_right haq)
      simpa only [y, sub_add_cancel] using hsum

/-- Circuit-facing form: the quadratic image of a flattened all-quadratic
prefix of defect at most one has a decomposable anchor modulo the target. -/
theorem exists_decomposable_anchor_of_quadraticPrefix
    {r j : Nat} (C : Circuit 10 r)
    (hflat : QuadraticPrefixFlattening C j)
    (hdef : Module.finrank F₂
      (presentationDefect hflat.generator) ≤ 1) :
    ∃ q : TwoForm,
      IsDecomposableTwo q ∧ q ∈ quadraticPrefixImage C j ∧
      presentationDefect hflat.generator = Submodule.span F₂
        ({quadraticQuotientProjection q} : Set QuadraticQuotient) ∧
      quadraticPrefixImage C j ≤
        targetTwoSpace ⊔ Submodule.span F₂ ({q} : Set TwoForm) := by
  rcases exists_decomposable_anchor_of_presentationDefect_le_one
      hflat.generator hflat.decomposable hdef with
    ⟨q, hqdec, hq, hprincipal, hspan⟩
  rw [hflat.span_eq] at hq hspan
  exact ⟨q, hqdec, hq, hprincipal, hspan⟩

/-- If an anchor covers a quadratic prefix modulo the full target and the
prefix's actual target wires lie in the first-order envelope, then the full
quadratic image is covered by the first-order envelope plus that anchor. -/
theorem quadraticPrefixImage_le_firstOrder_sup_anchor
    {r j : Nat} (C : Circuit 10 r)
    (hall : ∀ i : Fin r, i.val < j →
      C.gate i ∈ N4.quadraticANFSpace 10)
    (htarget : N4.circuitFlag C j ⊓
      N4.targetAmbient 10 (mulTarget 5) ≤ firstOrderEnvelopeState)
    (q : TwoForm) (hq : q ∈ quadraticPrefixImage C j)
    (hcover : quadraticPrefixImage C j ≤
      targetTwoSpace ⊔ Submodule.span F₂ ({q} : Set TwoForm)) :
    quadraticPrefixImage C j ≤
      firstOrderEnvelopeTwoSpace ⊔
        Submodule.span F₂ ({q} : Set TwoForm) := by
  rintro p ⟨x, hx, hxp⟩
  rcases hq with ⟨z, hz, hzq⟩
  have hpCover := hcover ⟨x, hx, hxp⟩
  rcases Submodule.mem_sup.mp hpCover with ⟨t, htT, s, hs, hsum⟩
  rcases Submodule.mem_span_singleton.mp hs with ⟨a, rfl⟩
  let y := x - a • z
  have hyV : y ∈ N4.circuitFlag C j :=
    (N4.circuitFlag C j).sub_mem hx ((N4.circuitFlag C j).smul_mem a hz)
  have hquadLe : N4.circuitFlag C j ≤ N4.quadraticANFSpace 10 :=
    N4.wireSpace_le_quadratic_of_prefix C.gate hall
  have hyquad : y ∈ N4.quadraticANFSpace 10 := hquadLe hyV
  have hyProjection : quadraticProjection 10 y = t := by
    simp only [y, map_sub, map_smul, hzq]
    rw [hxp, ← hsum]
    exact add_sub_cancel_right t (a • q)
  have hyTargetEnvelope : y ∈
      E2.quadraticEnvelopeState targetTwoSpace :=
    (E2.mem_quadraticEnvelopeState_iff targetTwoSpace y).2
      ⟨hyquad, hyProjection.symm ▸ htT⟩
  have hyAmbient : y ∈ N4.targetAmbient 10 (mulTarget 5) := by
    simpa [E2.quadraticEnvelopeState,
      E2.targetAmbient_eq_affine_sup_quadraticLift] using hyTargetEnvelope
  have hyFirst : y ∈ firstOrderEnvelopeState :=
    htarget ⟨hyV, hyAmbient⟩
  have htFirst : t ∈ firstOrderEnvelopeTwoSpace := by
    have hyProjectionMem :=
      ((E2.mem_quadraticEnvelopeState_iff
        firstOrderEnvelopeTwoSpace y).1 hyFirst).2
    rwa [hyProjection] at hyProjectionMem
  rw [← hsum]
  exact Submodule.add_mem _
    (Submodule.mem_sup_left htFirst)
    (Submodule.mem_sup_right
      (Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self q)))

/-- Every all-quadratic circuit prefix of semantic defect at most one has a
decomposable anchor whose span with the first-order envelope contains its
entire quadratic image. -/
theorem exists_firstOrder_decomposable_anchor_of_allQuadraticPrefix
    {r j : Nat} (C : Circuit 10 r) (hj : j ≤ r)
    (hall : AllQuadraticPrefix C j)
    (hdef : N4.flagDefectRank (N4.circuitFlag C j) (mulTarget 5) ≤ 1) :
    ∃ q : TwoForm,
      IsDecomposableTwo q ∧ q ∈ quadraticPrefixImage C j ∧
      quadraticPrefixImage C j ≤
        firstOrderEnvelopeTwoSpace ⊔
          Submodule.span F₂ ({q} : Set TwoForm) := by
  let hflat := quadraticPrefixFlattening_of_all_quadratic C hj hall
  have hpresentation : Module.finrank F₂
      (presentationDefect hflat.generator) ≤ 1 := by
    rw [quadraticPrefixFlattening_defect_eq_flagDefect C hflat hall]
    exact hdef
  rcases exists_decomposable_anchor_of_quadraticPrefix C hflat
      hpresentation with ⟨q, hqdec, hq, _hprincipal, hcover⟩
  have htarget : N4.circuitFlag C j ⊓
      N4.targetAmbient 10 (mulTarget 5) ≤ firstOrderEnvelopeState :=
    allQuadraticPrefix_target_le_firstOrder_of_flagDefect_le_one
      C hflat hall hdef
  exact ⟨q, hqdec, hq,
    quadraticPrefixImage_le_firstOrder_sup_anchor
      C hall htarget q hq hcover⟩

end
end N5
end UnrestrictedBooleanMul
