import UnrestrictedBooleanMul.N5.Capacity
import UnrestrictedBooleanMul.N4.Degree

/-!
# Unrestricted circuit prefixes

This file connects the generic circuit flag to the five-term quadratic
quotient.  It keeps semantic flattening as an explicit certificate: the
quadratic image of a prefix must equal a span of one decomposable form per
gate.  The following module constructs that certificate for an all-quadratic
prefix; the results here are the linear-algebraic interface used by every
suffix regime.
-/

namespace UnrestrictedBooleanMul
namespace N5

noncomputable section

/-- Quadratic image of the wire space after `j` gates. -/
def quadraticPrefixImage {r : Nat} (C : Circuit 10 r) (j : Nat) :
    Submodule F₂ TwoForm :=
  Submodule.map (quadraticProjection 10) (N4.circuitFlag C j)

/-- A semantic quadratic flattening of a prefix: its complete quadratic
image is generated by one decomposable form per prefix gate. -/
structure QuadraticPrefixFlattening {r : Nat} (C : Circuit 10 r) (j : Nat)
    where
  generator : Fin j → TwoForm
  decomposable : ∀ i, IsDecomposableTwo (generator i)
  span_eq : decomposablePresentationSpan generator = quadraticPrefixImage C j

/-- Target words are members of the multiplication target. -/
theorem targetANF_mem_mulTarget (c : TargetCoeff) :
    targetANF c ∈ mulTarget 5 := by
  apply Submodule.sum_mem
  intro i _
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

@[simp] theorem quadraticProjection_targetANF (c : TargetCoeff) :
    quadraticProjection 10 (targetANF c) = targetTwo c := by
  rfl

/-- Every element of the multiplication target has target-word coordinates. -/
theorem exists_targetCoeff_of_mem_mulTarget {t : ANF 10}
    (ht : t ∈ mulTarget 5) :
    ∃ c : TargetCoeff, targetANF c = t := by
  rw [mulTarget] at ht
  rcases (Submodule.mem_span_range_iff_exists_fun
      (R := F₂) (v := Mul 5) (x := t)).mp ht with ⟨c, hc⟩
  exact ⟨c, hc⟩

/-- The quadratic projection of `Aff + T` lands in the Hankel target. -/
theorem quadraticProjection_mem_targetTwoSpace_of_mem_targetAmbient
    {p : ANF 10} (hp : p ∈ N4.targetAmbient 10 (mulTarget 5)) :
    quadraticProjection 10 p ∈ targetTwoSpace := by
  rcases Submodule.mem_sup.mp hp with ⟨a, ha, t, ht, rfl⟩
  rcases exists_targetCoeff_of_mem_mulTarget ht with ⟨c, rfl⟩
  rw [map_add, quadraticProjection_kills_affine 10 ha, zero_add,
    quadraticProjection_targetANF]
  exact ⟨c, rfl⟩

/-- On `Aff + T`, vanishing quadratic projection means that the function is
already affine.  Target independence supplies the kernel calculation. -/
theorem mem_affine_of_mem_targetAmbient_of_quadraticProjection_eq_zero
    {p : ANF 10} (hp : p ∈ N4.targetAmbient 10 (mulTarget 5))
    (hzero : quadraticProjection 10 p = 0) :
    p ∈ affine 10 := by
  rcases Submodule.mem_sup.mp hp with ⟨a, ha, t, ht, hpat⟩
  rcases exists_targetCoeff_of_mem_mulTarget ht with ⟨c, hct⟩
  have hcTwo : targetTwo c = 0 := by
    calc
      targetTwo c = quadraticProjection 10 (targetANF c) :=
        (quadraticProjection_targetANF c).symm
      _ = quadraticProjection 10 t := congrArg (quadraticProjection 10) hct
      _ = quadraticProjection 10 p := by
        rw [← hpat, map_add, quadraticProjection_kills_affine 10 ha, zero_add]
      _ = 0 := hzero
  have hc : c = 0 := targetTwo_injective (hcTwo.trans (map_zero targetTwoLinear).symm)
  have ht0 : t = 0 := by
    rw [← hct, hc]
    simp [targetANF]
  rw [← hpat, ht0, add_zero]
  exact ha

/-- The flag target rank injects into the target part of the quadratic prefix
image.  No degree hypothesis is needed for this direction. -/
theorem flagTargetRank_le_quadraticPrefixTarget {r j : Nat}
    (C : Circuit 10 r) :
    N4.flagTargetRank (N4.circuitFlag C j) (mulTarget 5) ≤
      Module.finrank F₂
        ↑(targetTwoSpace ⊓ quadraticPrefixImage C j) := by
  let V := N4.circuitFlag C j
  let I := V ⊓ N4.targetAmbient 10 (mulTarget 5)
  let g : I →ₗ[F₂] TwoForm := (quadraticProjection 10).domRestrict I
  have hAffI : affine 10 ≤ I := by
    intro a ha
    exact ⟨affine_le_wireSpace C.gate ha, Submodule.mem_sup_left ha⟩
  have hker : LinearMap.ker g = (affine 10).comap I.subtype := by
    ext x
    constructor
    · intro hx
      have hx0 : quadraticProjection 10 x.1 = 0 :=
        LinearMap.mem_ker.mp hx
      exact mem_affine_of_mem_targetAmbient_of_quadraticProjection_eq_zero
        x.2.2 hx0
    · intro hx
      exact LinearMap.mem_ker.mpr (quadraticProjection_kills_affine 10 hx)
  have hkerRank : Module.finrank F₂ (LinearMap.ker g) =
      Module.finrank F₂ (affine 10) := by
    rw [hker]
    exact (Submodule.comapSubtypeEquivOfLe hAffI).finrank_eq
  have hRangeLe : LinearMap.range g ≤
      targetTwoSpace ⊓ quadraticPrefixImage C j := by
    rintro y ⟨x, rfl⟩
    constructor
    · exact quadraticProjection_mem_targetTwoSpace_of_mem_targetAmbient x.2.2
    · exact ⟨x.1, x.2.1, rfl⟩
  have hRangeRank : Module.finrank F₂ (LinearMap.range g) ≤
      Module.finrank F₂ ↑(targetTwoSpace ⊓ quadraticPrefixImage C j) :=
    Submodule.finrank_mono hRangeLe
  have hrank := g.finrank_range_add_finrank_ker
  rw [hkerRank] at hrank
  unfold N4.flagTargetRank
  change Module.finrank F₂ I - Module.finrank F₂ (affine 10) ≤ _
  omega

/-- The quotient defect of a flattened prefix is bounded by the circuit flag
defect. -/
theorem presentationDefect_le_flagDefect {r j : Nat}
    (C : Circuit 10 r) (hflat : QuadraticPrefixFlattening C j) :
    Module.finrank F₂ (presentationDefect hflat.generator) ≤
      N4.flagDefectRank (N4.circuitFlag C j) (mulTarget 5) := by
  let V := N4.circuitFlag C j
  let I := V ⊓ N4.targetAmbient 10 (mulTarget 5)
  let f : V →ₗ[F₂] QuadraticQuotient :=
    quadraticQuotientProjection.comp
      ((quadraticProjection 10).domRestrict V)
  have hrange : LinearMap.range f = presentationDefect hflat.generator := by
    apply le_antisymm
    · rintro y ⟨x, rfl⟩
      have hxImage : quadraticProjection 10 x.1 ∈ quadraticPrefixImage C j :=
        ⟨x.1, x.2, rfl⟩
      rw [← hflat.span_eq] at hxImage
      refine Submodule.span_induction (p := fun z _ =>
          quadraticQuotientProjection z ∈
            presentationDefect hflat.generator)
        ?_ ?_ ?_ ?_ hxImage
      · rintro _ ⟨i, rfl⟩
        exact Submodule.subset_span ⟨i, rfl⟩
      · simp
      · intro u v _ _ hu hv
        simpa using (presentationDefect hflat.generator).add_mem hu hv
      · intro a u _ hu
        simpa using (presentationDefect hflat.generator).smul_mem a hu
    · apply Submodule.span_le.mpr
      rintro _ ⟨i, rfl⟩
      have hiSpan : hflat.generator i ∈
          decomposablePresentationSpan hflat.generator :=
        Submodule.subset_span ⟨i, rfl⟩
      rw [hflat.span_eq] at hiSpan
      rcases hiSpan with ⟨x, hxV, hx⟩
      exact ⟨⟨x, hxV⟩, by simpa [f] using congrArg quadraticQuotientProjection hx⟩
  let inclusion : I →ₗ[F₂] V := {
    toFun x := ⟨x.1, x.2.1⟩
    map_add' x y := rfl
    map_smul' a x := rfl
  }
  have hinclusion : Function.Injective inclusion := by
    intro x y hxy
    apply Subtype.ext
    exact congrArg (fun z : V => z.1) hxy
  have hinclusionKer (x : I) : inclusion x ∈ LinearMap.ker f := by
    apply LinearMap.mem_ker.mpr
    change quadraticQuotientProjection (quadraticProjection 10 x.1) = 0
    apply (quadraticQuotientProjection_eq_zero_iff _).2
    exact quadraticProjection_mem_targetTwoSpace_of_mem_targetAmbient x.2.2
  let kernelInclusion : I →ₗ[F₂] LinearMap.ker f :=
    inclusion.codRestrict (LinearMap.ker f) hinclusionKer
  have hkernelInclusion : Function.Injective kernelInclusion := by
    intro x y hxy
    apply hinclusion
    exact congrArg (fun z : LinearMap.ker f => z.1) hxy
  have hIleKer : Module.finrank F₂ I ≤
      Module.finrank F₂ (LinearMap.ker f) :=
    kernelInclusion.finrank_le_finrank_of_injective hkernelInclusion
  have hrank := f.finrank_range_add_finrank_ker
  rw [hrange] at hrank
  unfold N4.flagDefectRank
  change Module.finrank F₂ (presentationDefect hflat.generator) ≤
    Module.finrank F₂ V - Module.finrank F₂ I
  omega

/-- Capacity form of the quadratic-prefix ledger. -/
theorem flattenedPrefix_targetRank_le_capacity {r j : Nat}
    (C : Circuit 10 r) (hflat : QuadraticPrefixFlattening C j) :
    N4.flagTargetRank (N4.circuitFlag C j) (mulTarget 5) ≤
      targetCapacity (presentationDefect hflat.generator) := by
  have ht := flagTargetRank_le_quadraticPrefixTarget (j := j) C
  have hspanGeo : quadraticPrefixImage C j ≤
      geometricCapacitySpan (presentationDefect hflat.generator) := by
    rw [← hflat.span_eq]
    exact decomposablePresentationSpan_le_geometricCapacitySpan
      hflat.generator hflat.decomposable
  have hinf : targetTwoSpace ⊓ quadraticPrefixImage C j ≤
      targetTwoSpace ⊓
        geometricCapacitySpan (presentationDefect hflat.generator) :=
    inf_le_inf le_rfl hspanGeo
  calc
    N4.flagTargetRank (N4.circuitFlag C j) (mulTarget 5) ≤
        Module.finrank F₂ ↑(targetTwoSpace ⊓ quadraticPrefixImage C j) := ht
    _ ≤ Module.finrank F₂
        ↑(targetTwoSpace ⊓
          geometricCapacitySpan (presentationDefect hflat.generator)) :=
      Submodule.finrank_mono hinf
    _ = targetCapacity (presentationDefect hflat.generator) := by
      rw [targetCapacity, defectCapacitySpan_eq_geometricCapacitySpan]

/-- Manuscript Lemma 9.1, the exact target--defect identity and the one-gate
target increment for a nonredundant prefix. -/
theorem circuit_bookkeeping {r j : Nat} (C : Circuit 10 r)
    (hj : j ≤ r)
    (hnr : ∀ i : Fin r, i.val < j → N4.NonredundantAt C i) :
    j = N4.flagTargetRank (N4.circuitFlag C j) (mulTarget 5) +
          N4.flagDefectRank (N4.circuitFlag C j) (mulTarget 5) ∧
      ∀ i : Fin r, i.val < j →
        N4.flagTargetRank (N4.circuitFlag C (i.val + 1)) (mulTarget 5) ≤
          N4.flagTargetRank (N4.circuitFlag C i.val) (mulTarget 5) + 1 := by
  constructor
  · exact N4.circuit_flag_defect_count C (mulTarget 5) hj hnr
  · intro i _
    exact N4.flagTargetRank_step_le_one C (mulTarget 5) i

/-- Full quadratic-prefix form of the circuit bookkeeping interface. -/
theorem circuit_bookkeeping_capacity {r j : Nat} (C : Circuit 10 r)
    (hj : j ≤ r)
    (hnr : ∀ i : Fin r, i.val < j → N4.NonredundantAt C i)
    (hflat : QuadraticPrefixFlattening C j) :
    j = N4.flagTargetRank (N4.circuitFlag C j) (mulTarget 5) +
          N4.flagDefectRank (N4.circuitFlag C j) (mulTarget 5) ∧
      N4.flagTargetRank (N4.circuitFlag C j) (mulTarget 5) ≤
        targetCapacity (presentationDefect hflat.generator) ∧
      Module.finrank F₂ (presentationDefect hflat.generator) ≤
        N4.flagDefectRank (N4.circuitFlag C j) (mulTarget 5) := by
  exact ⟨(circuit_bookkeeping C hj hnr).1,
    flattenedPrefix_targetRank_le_capacity C hflat,
    presentationDefect_le_flagDefect C hflat⟩

end

end N5
end UnrestrictedBooleanMul
