import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawBase
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part0
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part1
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part2
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part3
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part4
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part5
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part6
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part7
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part8
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part9
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part10
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part11
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part12
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part13
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part14
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part15
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part16
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part17
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part18
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part19
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part20
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part21
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part22
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part23
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part24
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part25
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part26
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part27
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part28
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part29
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part30
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part31
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part32
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part33
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part34
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part35
import UnrestrictedBooleanMul.N5.QuadraticReturnHistoryZeroOneRInfRawProducts2Product12Part36

namespace UnrestrictedBooleanMul.N5
noncomputable section
set_option linter.unreachableTactic false
set_option linter.unusedTactic false
set_option linter.unusedSimpArgs false
set_option linter.unnecessarySeqFocus false
set_option maxRecDepth 8192

def zeroOneRInfRawMultiplier_12 (v : Fin 71 → F₂) : F₂ :=
  zeroOneRInfRawMultiplier_12_part_0 v +
  zeroOneRInfRawMultiplier_12_part_1 v +
  zeroOneRInfRawMultiplier_12_part_2 v +
  zeroOneRInfRawMultiplier_12_part_3 v +
  zeroOneRInfRawMultiplier_12_part_4 v +
  zeroOneRInfRawMultiplier_12_part_5 v +
  zeroOneRInfRawMultiplier_12_part_6 v +
  zeroOneRInfRawMultiplier_12_part_7 v +
  zeroOneRInfRawMultiplier_12_part_8 v +
  zeroOneRInfRawMultiplier_12_part_9 v +
  zeroOneRInfRawMultiplier_12_part_10 v +
  zeroOneRInfRawMultiplier_12_part_11 v +
  zeroOneRInfRawMultiplier_12_part_12 v +
  zeroOneRInfRawMultiplier_12_part_13 v +
  zeroOneRInfRawMultiplier_12_part_14 v +
  zeroOneRInfRawMultiplier_12_part_15 v +
  zeroOneRInfRawMultiplier_12_part_16 v +
  zeroOneRInfRawMultiplier_12_part_17 v +
  zeroOneRInfRawMultiplier_12_part_18 v +
  zeroOneRInfRawMultiplier_12_part_19 v +
  zeroOneRInfRawMultiplier_12_part_20 v +
  zeroOneRInfRawMultiplier_12_part_21 v +
  zeroOneRInfRawMultiplier_12_part_22 v +
  zeroOneRInfRawMultiplier_12_part_23 v +
  zeroOneRInfRawMultiplier_12_part_24 v +
  zeroOneRInfRawMultiplier_12_part_25 v +
  zeroOneRInfRawMultiplier_12_part_26 v +
  zeroOneRInfRawMultiplier_12_part_27 v +
  zeroOneRInfRawMultiplier_12_part_28 v +
  zeroOneRInfRawMultiplier_12_part_29 v +
  zeroOneRInfRawMultiplier_12_part_30 v +
  zeroOneRInfRawMultiplier_12_part_31 v +
  zeroOneRInfRawMultiplier_12_part_32 v +
  zeroOneRInfRawMultiplier_12_part_33 v +
  zeroOneRInfRawMultiplier_12_part_34 v +
  zeroOneRInfRawMultiplier_12_part_35 v +
  zeroOneRInfRawMultiplier_12_part_36 v

def zeroOneRInfRawProduct_12 (v : Fin 71 → F₂) : F₂ :=
  zeroOneRInfRawProduct_12_part_0 v +
  zeroOneRInfRawProduct_12_part_1 v +
  zeroOneRInfRawProduct_12_part_2 v +
  zeroOneRInfRawProduct_12_part_3 v +
  zeroOneRInfRawProduct_12_part_4 v +
  zeroOneRInfRawProduct_12_part_5 v +
  zeroOneRInfRawProduct_12_part_6 v +
  zeroOneRInfRawProduct_12_part_7 v +
  zeroOneRInfRawProduct_12_part_8 v +
  zeroOneRInfRawProduct_12_part_9 v +
  zeroOneRInfRawProduct_12_part_10 v +
  zeroOneRInfRawProduct_12_part_11 v +
  zeroOneRInfRawProduct_12_part_12 v +
  zeroOneRInfRawProduct_12_part_13 v +
  zeroOneRInfRawProduct_12_part_14 v +
  zeroOneRInfRawProduct_12_part_15 v +
  zeroOneRInfRawProduct_12_part_16 v +
  zeroOneRInfRawProduct_12_part_17 v +
  zeroOneRInfRawProduct_12_part_18 v +
  zeroOneRInfRawProduct_12_part_19 v +
  zeroOneRInfRawProduct_12_part_20 v +
  zeroOneRInfRawProduct_12_part_21 v +
  zeroOneRInfRawProduct_12_part_22 v +
  zeroOneRInfRawProduct_12_part_23 v +
  zeroOneRInfRawProduct_12_part_24 v +
  zeroOneRInfRawProduct_12_part_25 v +
  zeroOneRInfRawProduct_12_part_26 v +
  zeroOneRInfRawProduct_12_part_27 v +
  zeroOneRInfRawProduct_12_part_28 v +
  zeroOneRInfRawProduct_12_part_29 v +
  zeroOneRInfRawProduct_12_part_30 v +
  zeroOneRInfRawProduct_12_part_31 v +
  zeroOneRInfRawProduct_12_part_32 v +
  zeroOneRInfRawProduct_12_part_33 v +
  zeroOneRInfRawProduct_12_part_34 v +
  zeroOneRInfRawProduct_12_part_35 v +
  zeroOneRInfRawProduct_12_part_36 v

set_option maxHeartbeats 3000000 in
theorem zeroOneRInfRaw_product_12 (v : Fin 71 → F₂) :
    zeroOneRInfRawMultiplier_12 v * zeroOneRInfRawConstraint v 12 =
      zeroOneRInfRawProduct_12 v := by
  have hpart_0 := zeroOneRInfRaw_product_12_part_0 v
  have hpart_1 := zeroOneRInfRaw_product_12_part_1 v
  have hpart_2 := zeroOneRInfRaw_product_12_part_2 v
  have hpart_3 := zeroOneRInfRaw_product_12_part_3 v
  have hpart_4 := zeroOneRInfRaw_product_12_part_4 v
  have hpart_5 := zeroOneRInfRaw_product_12_part_5 v
  have hpart_6 := zeroOneRInfRaw_product_12_part_6 v
  have hpart_7 := zeroOneRInfRaw_product_12_part_7 v
  have hpart_8 := zeroOneRInfRaw_product_12_part_8 v
  have hpart_9 := zeroOneRInfRaw_product_12_part_9 v
  have hpart_10 := zeroOneRInfRaw_product_12_part_10 v
  have hpart_11 := zeroOneRInfRaw_product_12_part_11 v
  have hpart_12 := zeroOneRInfRaw_product_12_part_12 v
  have hpart_13 := zeroOneRInfRaw_product_12_part_13 v
  have hpart_14 := zeroOneRInfRaw_product_12_part_14 v
  have hpart_15 := zeroOneRInfRaw_product_12_part_15 v
  have hpart_16 := zeroOneRInfRaw_product_12_part_16 v
  have hpart_17 := zeroOneRInfRaw_product_12_part_17 v
  have hpart_18 := zeroOneRInfRaw_product_12_part_18 v
  have hpart_19 := zeroOneRInfRaw_product_12_part_19 v
  have hpart_20 := zeroOneRInfRaw_product_12_part_20 v
  have hpart_21 := zeroOneRInfRaw_product_12_part_21 v
  have hpart_22 := zeroOneRInfRaw_product_12_part_22 v
  have hpart_23 := zeroOneRInfRaw_product_12_part_23 v
  have hpart_24 := zeroOneRInfRaw_product_12_part_24 v
  have hpart_25 := zeroOneRInfRaw_product_12_part_25 v
  have hpart_26 := zeroOneRInfRaw_product_12_part_26 v
  have hpart_27 := zeroOneRInfRaw_product_12_part_27 v
  have hpart_28 := zeroOneRInfRaw_product_12_part_28 v
  have hpart_29 := zeroOneRInfRaw_product_12_part_29 v
  have hpart_30 := zeroOneRInfRaw_product_12_part_30 v
  have hpart_31 := zeroOneRInfRaw_product_12_part_31 v
  have hpart_32 := zeroOneRInfRaw_product_12_part_32 v
  have hpart_33 := zeroOneRInfRaw_product_12_part_33 v
  have hpart_34 := zeroOneRInfRaw_product_12_part_34 v
  have hpart_35 := zeroOneRInfRaw_product_12_part_35 v
  have hpart_36 := zeroOneRInfRaw_product_12_part_36 v
  have hsum_0 :
      zeroOneRInfRawMultiplier_12_part_0 v * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v := hpart_0
  have hsum_1 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v := by
    rw [add_mul, hsum_0, hpart_1]
  have hsum_2 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v := by
    rw [add_mul, hsum_1, hpart_2]
  have hsum_3 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v := by
    rw [add_mul, hsum_2, hpart_3]
  have hsum_4 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v := by
    rw [add_mul, hsum_3, hpart_4]
  have hsum_5 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v := by
    rw [add_mul, hsum_4, hpart_5]
  have hsum_6 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v := by
    rw [add_mul, hsum_5, hpart_6]
  have hsum_7 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v := by
    rw [add_mul, hsum_6, hpart_7]
  have hsum_8 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v := by
    rw [add_mul, hsum_7, hpart_8]
  have hsum_9 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v := by
    rw [add_mul, hsum_8, hpart_9]
  have hsum_10 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v := by
    rw [add_mul, hsum_9, hpart_10]
  have hsum_11 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v := by
    rw [add_mul, hsum_10, hpart_11]
  have hsum_12 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v := by
    rw [add_mul, hsum_11, hpart_12]
  have hsum_13 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v := by
    rw [add_mul, hsum_12, hpart_13]
  have hsum_14 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v := by
    rw [add_mul, hsum_13, hpart_14]
  have hsum_15 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v := by
    rw [add_mul, hsum_14, hpart_15]
  have hsum_16 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v := by
    rw [add_mul, hsum_15, hpart_16]
  have hsum_17 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v := by
    rw [add_mul, hsum_16, hpart_17]
  have hsum_18 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v := by
    rw [add_mul, hsum_17, hpart_18]
  have hsum_19 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v := by
    rw [add_mul, hsum_18, hpart_19]
  have hsum_20 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v := by
    rw [add_mul, hsum_19, hpart_20]
  have hsum_21 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v := by
    rw [add_mul, hsum_20, hpart_21]
  have hsum_22 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v := by
    rw [add_mul, hsum_21, hpart_22]
  have hsum_23 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v := by
    rw [add_mul, hsum_22, hpart_23]
  have hsum_24 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v := by
    rw [add_mul, hsum_23, hpart_24]
  have hsum_25 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v + zeroOneRInfRawMultiplier_12_part_25 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v + zeroOneRInfRawProduct_12_part_25 v := by
    rw [add_mul, hsum_24, hpart_25]
  have hsum_26 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v + zeroOneRInfRawMultiplier_12_part_25 v + zeroOneRInfRawMultiplier_12_part_26 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v + zeroOneRInfRawProduct_12_part_25 v + zeroOneRInfRawProduct_12_part_26 v := by
    rw [add_mul, hsum_25, hpart_26]
  have hsum_27 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v + zeroOneRInfRawMultiplier_12_part_25 v + zeroOneRInfRawMultiplier_12_part_26 v + zeroOneRInfRawMultiplier_12_part_27 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v + zeroOneRInfRawProduct_12_part_25 v + zeroOneRInfRawProduct_12_part_26 v + zeroOneRInfRawProduct_12_part_27 v := by
    rw [add_mul, hsum_26, hpart_27]
  have hsum_28 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v + zeroOneRInfRawMultiplier_12_part_25 v + zeroOneRInfRawMultiplier_12_part_26 v + zeroOneRInfRawMultiplier_12_part_27 v + zeroOneRInfRawMultiplier_12_part_28 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v + zeroOneRInfRawProduct_12_part_25 v + zeroOneRInfRawProduct_12_part_26 v + zeroOneRInfRawProduct_12_part_27 v + zeroOneRInfRawProduct_12_part_28 v := by
    rw [add_mul, hsum_27, hpart_28]
  have hsum_29 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v + zeroOneRInfRawMultiplier_12_part_25 v + zeroOneRInfRawMultiplier_12_part_26 v + zeroOneRInfRawMultiplier_12_part_27 v + zeroOneRInfRawMultiplier_12_part_28 v + zeroOneRInfRawMultiplier_12_part_29 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v + zeroOneRInfRawProduct_12_part_25 v + zeroOneRInfRawProduct_12_part_26 v + zeroOneRInfRawProduct_12_part_27 v + zeroOneRInfRawProduct_12_part_28 v + zeroOneRInfRawProduct_12_part_29 v := by
    rw [add_mul, hsum_28, hpart_29]
  have hsum_30 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v + zeroOneRInfRawMultiplier_12_part_25 v + zeroOneRInfRawMultiplier_12_part_26 v + zeroOneRInfRawMultiplier_12_part_27 v + zeroOneRInfRawMultiplier_12_part_28 v + zeroOneRInfRawMultiplier_12_part_29 v + zeroOneRInfRawMultiplier_12_part_30 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v + zeroOneRInfRawProduct_12_part_25 v + zeroOneRInfRawProduct_12_part_26 v + zeroOneRInfRawProduct_12_part_27 v + zeroOneRInfRawProduct_12_part_28 v + zeroOneRInfRawProduct_12_part_29 v + zeroOneRInfRawProduct_12_part_30 v := by
    rw [add_mul, hsum_29, hpart_30]
  have hsum_31 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v + zeroOneRInfRawMultiplier_12_part_25 v + zeroOneRInfRawMultiplier_12_part_26 v + zeroOneRInfRawMultiplier_12_part_27 v + zeroOneRInfRawMultiplier_12_part_28 v + zeroOneRInfRawMultiplier_12_part_29 v + zeroOneRInfRawMultiplier_12_part_30 v + zeroOneRInfRawMultiplier_12_part_31 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v + zeroOneRInfRawProduct_12_part_25 v + zeroOneRInfRawProduct_12_part_26 v + zeroOneRInfRawProduct_12_part_27 v + zeroOneRInfRawProduct_12_part_28 v + zeroOneRInfRawProduct_12_part_29 v + zeroOneRInfRawProduct_12_part_30 v + zeroOneRInfRawProduct_12_part_31 v := by
    rw [add_mul, hsum_30, hpart_31]
  have hsum_32 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v + zeroOneRInfRawMultiplier_12_part_25 v + zeroOneRInfRawMultiplier_12_part_26 v + zeroOneRInfRawMultiplier_12_part_27 v + zeroOneRInfRawMultiplier_12_part_28 v + zeroOneRInfRawMultiplier_12_part_29 v + zeroOneRInfRawMultiplier_12_part_30 v + zeroOneRInfRawMultiplier_12_part_31 v + zeroOneRInfRawMultiplier_12_part_32 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v + zeroOneRInfRawProduct_12_part_25 v + zeroOneRInfRawProduct_12_part_26 v + zeroOneRInfRawProduct_12_part_27 v + zeroOneRInfRawProduct_12_part_28 v + zeroOneRInfRawProduct_12_part_29 v + zeroOneRInfRawProduct_12_part_30 v + zeroOneRInfRawProduct_12_part_31 v + zeroOneRInfRawProduct_12_part_32 v := by
    rw [add_mul, hsum_31, hpart_32]
  have hsum_33 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v + zeroOneRInfRawMultiplier_12_part_25 v + zeroOneRInfRawMultiplier_12_part_26 v + zeroOneRInfRawMultiplier_12_part_27 v + zeroOneRInfRawMultiplier_12_part_28 v + zeroOneRInfRawMultiplier_12_part_29 v + zeroOneRInfRawMultiplier_12_part_30 v + zeroOneRInfRawMultiplier_12_part_31 v + zeroOneRInfRawMultiplier_12_part_32 v + zeroOneRInfRawMultiplier_12_part_33 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v + zeroOneRInfRawProduct_12_part_25 v + zeroOneRInfRawProduct_12_part_26 v + zeroOneRInfRawProduct_12_part_27 v + zeroOneRInfRawProduct_12_part_28 v + zeroOneRInfRawProduct_12_part_29 v + zeroOneRInfRawProduct_12_part_30 v + zeroOneRInfRawProduct_12_part_31 v + zeroOneRInfRawProduct_12_part_32 v + zeroOneRInfRawProduct_12_part_33 v := by
    rw [add_mul, hsum_32, hpart_33]
  have hsum_34 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v + zeroOneRInfRawMultiplier_12_part_25 v + zeroOneRInfRawMultiplier_12_part_26 v + zeroOneRInfRawMultiplier_12_part_27 v + zeroOneRInfRawMultiplier_12_part_28 v + zeroOneRInfRawMultiplier_12_part_29 v + zeroOneRInfRawMultiplier_12_part_30 v + zeroOneRInfRawMultiplier_12_part_31 v + zeroOneRInfRawMultiplier_12_part_32 v + zeroOneRInfRawMultiplier_12_part_33 v + zeroOneRInfRawMultiplier_12_part_34 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v + zeroOneRInfRawProduct_12_part_25 v + zeroOneRInfRawProduct_12_part_26 v + zeroOneRInfRawProduct_12_part_27 v + zeroOneRInfRawProduct_12_part_28 v + zeroOneRInfRawProduct_12_part_29 v + zeroOneRInfRawProduct_12_part_30 v + zeroOneRInfRawProduct_12_part_31 v + zeroOneRInfRawProduct_12_part_32 v + zeroOneRInfRawProduct_12_part_33 v + zeroOneRInfRawProduct_12_part_34 v := by
    rw [add_mul, hsum_33, hpart_34]
  have hsum_35 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v + zeroOneRInfRawMultiplier_12_part_25 v + zeroOneRInfRawMultiplier_12_part_26 v + zeroOneRInfRawMultiplier_12_part_27 v + zeroOneRInfRawMultiplier_12_part_28 v + zeroOneRInfRawMultiplier_12_part_29 v + zeroOneRInfRawMultiplier_12_part_30 v + zeroOneRInfRawMultiplier_12_part_31 v + zeroOneRInfRawMultiplier_12_part_32 v + zeroOneRInfRawMultiplier_12_part_33 v + zeroOneRInfRawMultiplier_12_part_34 v + zeroOneRInfRawMultiplier_12_part_35 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v + zeroOneRInfRawProduct_12_part_25 v + zeroOneRInfRawProduct_12_part_26 v + zeroOneRInfRawProduct_12_part_27 v + zeroOneRInfRawProduct_12_part_28 v + zeroOneRInfRawProduct_12_part_29 v + zeroOneRInfRawProduct_12_part_30 v + zeroOneRInfRawProduct_12_part_31 v + zeroOneRInfRawProduct_12_part_32 v + zeroOneRInfRawProduct_12_part_33 v + zeroOneRInfRawProduct_12_part_34 v + zeroOneRInfRawProduct_12_part_35 v := by
    rw [add_mul, hsum_34, hpart_35]
  have hsum_36 :
      (zeroOneRInfRawMultiplier_12_part_0 v + zeroOneRInfRawMultiplier_12_part_1 v + zeroOneRInfRawMultiplier_12_part_2 v + zeroOneRInfRawMultiplier_12_part_3 v + zeroOneRInfRawMultiplier_12_part_4 v + zeroOneRInfRawMultiplier_12_part_5 v + zeroOneRInfRawMultiplier_12_part_6 v + zeroOneRInfRawMultiplier_12_part_7 v + zeroOneRInfRawMultiplier_12_part_8 v + zeroOneRInfRawMultiplier_12_part_9 v + zeroOneRInfRawMultiplier_12_part_10 v + zeroOneRInfRawMultiplier_12_part_11 v + zeroOneRInfRawMultiplier_12_part_12 v + zeroOneRInfRawMultiplier_12_part_13 v + zeroOneRInfRawMultiplier_12_part_14 v + zeroOneRInfRawMultiplier_12_part_15 v + zeroOneRInfRawMultiplier_12_part_16 v + zeroOneRInfRawMultiplier_12_part_17 v + zeroOneRInfRawMultiplier_12_part_18 v + zeroOneRInfRawMultiplier_12_part_19 v + zeroOneRInfRawMultiplier_12_part_20 v + zeroOneRInfRawMultiplier_12_part_21 v + zeroOneRInfRawMultiplier_12_part_22 v + zeroOneRInfRawMultiplier_12_part_23 v + zeroOneRInfRawMultiplier_12_part_24 v + zeroOneRInfRawMultiplier_12_part_25 v + zeroOneRInfRawMultiplier_12_part_26 v + zeroOneRInfRawMultiplier_12_part_27 v + zeroOneRInfRawMultiplier_12_part_28 v + zeroOneRInfRawMultiplier_12_part_29 v + zeroOneRInfRawMultiplier_12_part_30 v + zeroOneRInfRawMultiplier_12_part_31 v + zeroOneRInfRawMultiplier_12_part_32 v + zeroOneRInfRawMultiplier_12_part_33 v + zeroOneRInfRawMultiplier_12_part_34 v + zeroOneRInfRawMultiplier_12_part_35 v + zeroOneRInfRawMultiplier_12_part_36 v) * zeroOneRInfRawConstraint v 12 =
        zeroOneRInfRawProduct_12_part_0 v + zeroOneRInfRawProduct_12_part_1 v + zeroOneRInfRawProduct_12_part_2 v + zeroOneRInfRawProduct_12_part_3 v + zeroOneRInfRawProduct_12_part_4 v + zeroOneRInfRawProduct_12_part_5 v + zeroOneRInfRawProduct_12_part_6 v + zeroOneRInfRawProduct_12_part_7 v + zeroOneRInfRawProduct_12_part_8 v + zeroOneRInfRawProduct_12_part_9 v + zeroOneRInfRawProduct_12_part_10 v + zeroOneRInfRawProduct_12_part_11 v + zeroOneRInfRawProduct_12_part_12 v + zeroOneRInfRawProduct_12_part_13 v + zeroOneRInfRawProduct_12_part_14 v + zeroOneRInfRawProduct_12_part_15 v + zeroOneRInfRawProduct_12_part_16 v + zeroOneRInfRawProduct_12_part_17 v + zeroOneRInfRawProduct_12_part_18 v + zeroOneRInfRawProduct_12_part_19 v + zeroOneRInfRawProduct_12_part_20 v + zeroOneRInfRawProduct_12_part_21 v + zeroOneRInfRawProduct_12_part_22 v + zeroOneRInfRawProduct_12_part_23 v + zeroOneRInfRawProduct_12_part_24 v + zeroOneRInfRawProduct_12_part_25 v + zeroOneRInfRawProduct_12_part_26 v + zeroOneRInfRawProduct_12_part_27 v + zeroOneRInfRawProduct_12_part_28 v + zeroOneRInfRawProduct_12_part_29 v + zeroOneRInfRawProduct_12_part_30 v + zeroOneRInfRawProduct_12_part_31 v + zeroOneRInfRawProduct_12_part_32 v + zeroOneRInfRawProduct_12_part_33 v + zeroOneRInfRawProduct_12_part_34 v + zeroOneRInfRawProduct_12_part_35 v + zeroOneRInfRawProduct_12_part_36 v := by
    rw [add_mul, hsum_35, hpart_36]
  unfold zeroOneRInfRawMultiplier_12 zeroOneRInfRawProduct_12
  exact hsum_36

end
end UnrestrictedBooleanMul.N5
