import UnrestrictedBooleanMul.N5.FirstOrderColourReduction

/-!
# Removing the old correction colour in the rank-one branch

After rank-one factor normalization, suppose the old correction has no high
class outside the line generated by the high factor `U`.  Over `F₂` one may
toggle the quadratic factor by a scalar constant and simultaneously add the
same scalar multiple of `U` to the correction.  The wire extension and target
equation are unchanged, while the new correction is quadratic.  This is the
precise algebraic rewiring step in manuscript Lemma 12.2.
-/

namespace UnrestrictedBooleanMul
namespace N5

noncomputable section

private abbrev HighQuotient :=
  (ANF 10) ⧸ N4.quadraticANFSpace 10

/-- Adding an old wire to a proposed new generator does not change the
one-dimensional extension of the old state. -/
theorem sup_span_add_old_eq
    (V : Submodule F₂ (ANF 10)) (z w : ANF 10) (hw : w ∈ V) :
    V ⊔ Submodule.span F₂ ({z + w} : Set (ANF 10)) =
      V ⊔ Submodule.span F₂ ({z} : Set (ANF 10)) := by
  apply le_antisymm
  · apply sup_le le_sup_left
    rw [Submodule.span_le]
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact Submodule.add_mem _
      ((le_sup_right : Submodule.span F₂ ({z} : Set (ANF 10)) ≤ _)
        (Submodule.mem_span_singleton_self z))
      ((le_sup_left : V ≤ _) hw)
  · apply sup_le le_sup_left
    rw [Submodule.span_le]
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    have hsum : (z + w) + w ∈
        V ⊔ Submodule.span F₂ ({z + w} : Set (ANF 10)) :=
      Submodule.add_mem _
        ((le_sup_right : Submodule.span F₂ ({z + w} : Set (ANF 10)) ≤ _)
          (Submodule.mem_span_singleton_self (z + w)))
        ((le_sup_left : V ≤ _) hw)
    change z ∈ V ⊔ Submodule.span F₂ ({z + w} : Set (ANF 10))
    simpa only [add_assoc, anf_add_self, add_zero] using hsum

/-- If a correction's high class lies on the normalized factor line, toggle
the quadratic factor by a constant so the new correction is genuinely
degree at most two. -/
theorem exists_rankOne_rewiring_with_quadratic_correction
    (V : Submodule F₂ (ANF 10)) (U c t v : ANF 10)
    (hU : U ∈ V) (hc : c ∈ V)
    (hone : (1 : ANF 10) ∈ V)
    (hcquad : c ∈ N4.quadraticANFSpace 10)
    (heq : U * c = t + v)
    (hv : v ∈ V)
    (hvLine : Submodule.mkQ (N4.quadraticANFSpace 10) v ∈
      Submodule.span F₂
        ({Submodule.mkQ (N4.quadraticANFSpace 10) U} :
          Set ((ANF 10) ⧸ N4.quadraticANFSpace 10))) :
    ∃ c' v' : ANF 10,
      c' ∈ V ∧ c' ∈ N4.quadraticANFSpace 10 ∧
      v' ∈ V ∧ v' ∈ N4.quadraticANFSpace 10 ∧
      andExtend V U c' = andExtend V U c ∧
      U * c' = t + v' ∧
      U * (U * c') = U * c' ∧
      (U * c') * c' = U * c' := by
  rcases Submodule.mem_span_singleton.mp hvLine with ⟨a, ha⟩
  let c' : ANF 10 := c + a • (1 : ANF 10)
  let v' : ANF 10 := v + a • U
  have hc'V : c' ∈ V :=
    V.add_mem hc (V.smul_mem a hone)
  have hc'quad : c' ∈ N4.quadraticANFSpace 10 := by
    apply (N4.quadraticANFSpace 10).add_mem hcquad
    exact (N4.quadraticANFSpace 10).smul_mem a
      (N4.affine_le_quadraticANFSpace (one_mem_affine 10))
  have hv'V : v' ∈ V := V.add_mem hv (V.smul_mem a hU)
  have hv'quad : v' ∈ N4.quadraticANFSpace 10 := by
    apply (Submodule.Quotient.mk_eq_zero
      (N4.quadraticANFSpace 10)).mp
    change Submodule.mkQ (N4.quadraticANFSpace 10) (v + a • U) = 0
    rw [map_add, map_smul, ha]
    calc
      Submodule.mkQ (N4.quadraticANFSpace 10) v +
          Submodule.mkQ (N4.quadraticANFSpace 10) v =
        ((1 : F₂) + 1) •
          Submodule.mkQ (N4.quadraticANFSpace 10) v := by
            rw [add_smul, one_smul]
      _ = 0 := by rw [CharTwo.add_self_eq_zero, zero_smul]
  have hproduct : U * c' = U * c + a • U := by
    simp only [c', mul_add, mul_smul_comm, mul_one]
  have heq' : U * c' = t + v' := by
    rw [hproduct, heq]
    change (t + v) + a • U = t + (v + a • U)
    ac_rfl
  have hextend : andExtend V U c' = andExtend V U c := by
    unfold andExtend
    rw [hproduct]
    exact sup_span_add_old_eq V (U * c) (a • U) (V.smul_mem a hU)
  exact ⟨c', v', hc'V, hc'quad, hv'V, hv'quad, hextend, heq',
    N4.left_absorbs_product U c', N4.right_absorbs_product U c'⟩

/-- Every state reachable from a canonical anchor contains the constant one,
so the preceding colour-removal rewiring is always available there. -/
theorem one_mem_of_defectLegalSuffix_firstOrderAnchor
    (q : TwoForm) {V : Submodule F₂ (ANF 10)}
    (hreach : DefectLegalSuffix (firstOrderAnchorState q) V) :
    (1 : ANF 10) ∈ V := by
  exact hreach.start_le
    (E2.affine_le_quadraticEnvelopeState (firstOrderAnchorTwoSpace q)
      (one_mem_affine 10))

/-- In a state of high rank at most one, every high class lies on the line
of any fixed nonquadratic member. -/
theorem highClass_mem_span_of_stateHighRank_le_one
    (V : Submodule F₂ (ANF 10)) (U v : ANF 10)
    (hU : U ∈ V) (hv : v ∈ V)
    (hUhigh : U ∉ N4.quadraticANFSpace 10)
    (hhigh : stateHighRank V ≤ 1) :
    Submodule.mkQ (N4.quadraticANFSpace 10) v ∈
      Submodule.span F₂
        ({Submodule.mkQ (N4.quadraticANFSpace 10) U} :
          Set ((ANF 10) ⧸ N4.quadraticANFSpace 10)) := by
  let uQ := Submodule.mkQ (N4.quadraticANFSpace 10) U
  have huQ : uQ ∈ stateHighImage V := ⟨U, hU, rfl⟩
  have hvQ : Submodule.mkQ (N4.quadraticANFSpace 10) v ∈
      stateHighImage V := ⟨v, hv, rfl⟩
  have huQne : uQ ≠ 0 := by
    intro hzero
    exact hUhigh ((Submodule.Quotient.mk_eq_zero _).1 hzero)
  have hlineLe : Submodule.span F₂ ({uQ} : Set HighQuotient) ≤
      stateHighImage V := by
    rw [Submodule.span_le]
    simpa using huQ
  have hlower := Submodule.finrank_mono hlineLe
  rw [finrank_span_singleton huQne, stateHighImage_finrank] at hlower
  have himageRank : Module.finrank F₂ (stateHighImage V) = 1 := by
    rw [stateHighImage_finrank]
    omega
  have himageEq : stateHighImage V =
      Submodule.span F₂ ({uQ} : Set HighQuotient) :=
    eq_span_singleton_of_mem_of_finrank_eq_one himageRank huQ huQne
  rw [← himageEq]
  exact hvQ

/-- Therefore the quadratic-correction rewiring is automatic in every state
of high rank at most one that contains the affine inputs. -/
theorem exists_rankOne_rewiring_of_stateHighRank_le_one
    (V : Submodule F₂ (ANF 10)) (U c t v : ANF 10)
    (hAff : affine 10 ≤ V)
    (hU : U ∈ V) (hc : c ∈ V)
    (hUhigh : U ∉ N4.quadraticANFSpace 10)
    (hcquad : c ∈ N4.quadraticANFSpace 10)
    (heq : U * c = t + v) (hv : v ∈ V)
    (hhigh : stateHighRank V ≤ 1) :
    ∃ c' v' : ANF 10,
      c' ∈ V ∧ c' ∈ N4.quadraticANFSpace 10 ∧
      v' ∈ V ∧ v' ∈ N4.quadraticANFSpace 10 ∧
      andExtend V U c' = andExtend V U c ∧
      U * c' = t + v' ∧
      U * (U * c') = U * c' ∧
      (U * c') * c' = U * c' := by
  apply exists_rankOne_rewiring_with_quadratic_correction
    V U c t v hU hc (hAff (one_mem_affine 10)) hcquad heq hv
  exact highClass_mem_span_of_stateHighRank_le_one
    V U v hU hv hUhigh hhigh

end
end N5
end UnrestrictedBooleanMul
